'use client';
import {useEffect,useMemo,useState} from 'react';
import type {ClipboardEvent} from 'react';
import type {Director,SalesPerson} from '@/lib/types';
import UiIcon from './UiIcon';
import PaginationBar from './PaginationBar';
import LoadingOverlay from './LoadingOverlay';

type AttentionRow={id?:string;name:string;active:boolean};
type ClientGroup={client:string;address:string;active:boolean;attentions:AttentionRow[]};
type SalesDraftRow={name:string;email:string;phone:string;active:boolean};
type BatchClientRow={client:string;address:string;attention:string;active:boolean};
const alpha=(a:string,b:string)=>a.localeCompare(b,undefined,{sensitivity:'base'});
const emptyAttention=():AttentionRow=>({name:'',active:true});
const emptySales=():SalesDraftRow=>({name:'',email:'',phone:'',active:true});
const emptyBatch=():BatchClientRow=>({client:'',address:'',attention:'',active:true});
const padAttention=(rows:AttentionRow[],minimum=10)=>[...rows.map(x=>({...x})),...Array.from({length:Math.max(0,minimum-rows.length)},()=>emptyAttention())].slice(0,100);
const tenAttention=()=>Array.from({length:10},()=>emptyAttention());
const tenSales=()=>Array.from({length:10},()=>emptySales());
const tenBatch=()=>Array.from({length:10},()=>emptyBatch());
const boolFromPaste=(v:string)=>!/^(0|false|no|n|inactive)$/i.test(v.trim());

export default function DatabaseApp(){
 const [clients,setClients]=useState<ClientGroup[]>([]),[sales,setSales]=useState<SalesPerson[]>([]),[directors,setDirectors]=useState<Director[]>([]);
 const [search,setSearch]=useState(''),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(25),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const [clientModal,setClientModal]=useState(false),[originalClient,setOriginalClient]=useState(''),[draftClient,setDraftClient]=useState<ClientGroup>({client:'',address:'',active:true,attentions:tenAttention()}),[attentionRowsToAdd,setAttentionRowsToAdd]=useState(10);
 const [batchModal,setBatchModal]=useState(false),[batchRows,setBatchRows]=useState<BatchClientRow[]>(tenBatch()),[batchRowsToAdd,setBatchRowsToAdd]=useState(10);
 const [salesModal,setSalesModal]=useState(false),[salesDraft,setSalesDraft]=useState<SalesDraftRow[]>(tenSales()),[salesRowsToAdd,setSalesRowsToAdd]=useState(10);
 const [dirtySales,setDirtySales]=useState<Set<string>>(new Set()),[dirtyDirectors,setDirtyDirectors]=useState<Set<string>>(new Set());

 async function load(){
  setLoading(true);try{
   const [cr,mr]=await Promise.all([fetch('/api/clients',{cache:'no-store'}),fetch('/api/masters?scope=core',{cache:'no-store'})]);
   const [cj,mj]=await Promise.all([cr.json(),mr.json()]);if(!cr.ok)throw new Error(cj.error||'Failed to load Client Data');if(!mr.ok)throw new Error(mj.error||'Failed to load master data');
   setClients((cj||[]).sort((a:ClientGroup,b:ClientGroup)=>alpha(a.client,b.client)));setSales((mj.sales||[]).sort((a:SalesPerson,b:SalesPerson)=>alpha(a.name,b.name)));setDirectors((mj.directors||[]).sort((a:Director,b:Director)=>alpha(a.name,b.name)));setDirtySales(new Set());setDirtyDirectors(new Set());
  }catch(e){setMsg(e instanceof Error?e.message:'Failed to load Master Data')}finally{setLoading(false)}
 }
 useEffect(()=>{void load()},[]);

 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return clients.filter(c=>!q||[c.client,c.address,...c.attentions.map(a=>a.name)].join(' ').toLowerCase().includes(q))},[clients,search]);
 const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)),safePage=Math.min(page,totalPages),paged=filtered.slice((safePage-1)*pageSize,safePage*pageSize);
 useEffect(()=>{if(page>totalPages)setPage(totalPages)},[page,totalPages]);

 function openNewClient(){setOriginalClient('');setDraftClient({client:'',address:'',active:true,attentions:tenAttention()});setAttentionRowsToAdd(10);setClientModal(true)}
 function openEditClient(c:ClientGroup){setOriginalClient(c.client);setDraftClient({client:c.client,address:c.address||'',active:c.active,attentions:padAttention(c.attentions)});setAttentionRowsToAdd(10);setClientModal(true)}
 function matchExistingClient(name:string){const found=clients.find(c=>c.client.trim().toLowerCase()===name.trim().toLowerCase());if(found&&!originalClient){setOriginalClient(found.client);setDraftClient({client:found.client,address:found.address||'',active:found.active,attentions:padAttention(found.attentions)})}else setDraftClient(d=>({...d,client:name}))}
 function patchAttention(i:number,key:keyof AttentionRow,v:string|boolean){setDraftClient(d=>({...d,attentions:d.attentions.map((a,j)=>j===i?{...a,[key]:v}:a)}))}
 function addAttentionRows(){const room=Math.max(0,100-draftClient.attentions.length),count=Math.min(room,Math.max(1,attentionRowsToAdd));if(!count)return;setDraftClient(d=>({...d,attentions:[...d.attentions,...Array.from({length:count},()=>emptyAttention())]}))}
 function removeAttention(i:number){setDraftClient(d=>({...d,attentions:d.attentions.length<=10?d.attentions.map((a,j)=>j===i?emptyAttention():a):d.attentions.filter((_,j)=>j!==i)}))}
 function pasteAttention(e:ClipboardEvent<HTMLInputElement>,rowIndex:number,startCol:0|1){const raw=e.clipboardData.getData('text/plain');if(!raw.includes('\t')&&!raw.includes('\n'))return;e.preventDefault();const matrix=raw.replace(/\r/g,'').split('\n').filter((x,i,a)=>x||i<a.length-1).map(x=>x.split('\t'));setDraftClient(d=>{const rows=[...d.attentions.map(x=>({...x}))];while(rows.length<Math.min(100,rowIndex+matrix.length))rows.push(emptyAttention());matrix.forEach((line,ri)=>{const target=rowIndex+ri;if(target>=100)return;line.forEach((value,ci)=>{const col=startCol+ci;if(col===0)rows[target].name=value;if(col===1)rows[target].active=boolFromPaste(value)})});return {...d,attentions:rows}})}
 async function saveClient(){setBusy(true);setMsg('');try{const method=originalClient?'PATCH':'POST';const payload={...draftClient,originalClient:originalClient||undefined,attentions:draftClient.attentions.filter(a=>a.name.trim()).sort((a,b)=>alpha(a.name,b.name))};const r=await fetch('/api/clients',{method,headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok)throw new Error(j.error||'Failed to save client');setClientModal(false);setMsg(`${draftClient.client} saved.`);await load()}catch(e){setMsg(e instanceof Error?e.message:'Failed to save client')}finally{setBusy(false)}}
 async function deleteClient(c:ClientGroup){if(!confirm(`Delete ${c.client} and all Attention data?`))return;const r=await fetch('/api/clients',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({client:c.client})}),j=await r.json();if(!r.ok)return setMsg(j.error||'Delete failed');setMsg(`${c.client} deleted.`);await load()}

 function patchBatch(i:number,key:keyof BatchClientRow,v:string|boolean){setBatchRows(rows=>rows.map((r,j)=>j===i?{...r,[key]:v}:r))}
 function addBatchRows(){const count=Math.min(500,Math.max(1,batchRowsToAdd));setBatchRows(rows=>[...rows,...Array.from({length:count},()=>emptyBatch())].slice(0,500))}
 function removeBatchRow(i:number){setBatchRows(rows=>rows.length<=10?rows.map((r,j)=>j===i?emptyBatch():r):rows.filter((_,j)=>j!==i))}
 function pasteBatch(e:ClipboardEvent<HTMLInputElement>,rowIndex:number,startCol:0|1|2){const raw=e.clipboardData.getData('text/plain');if(!raw.includes('\t')&&!raw.includes('\n'))return;e.preventDefault();const matrix=raw.replace(/\r/g,'').split('\n').filter((x,i,a)=>x||i<a.length-1).map(x=>x.split('\t'));setBatchRows(current=>{const rows=current.map(x=>({...x}));while(rows.length<Math.min(500,rowIndex+matrix.length))rows.push(emptyBatch());matrix.forEach((line,ri)=>{const target=rowIndex+ri;if(target>=500)return;line.forEach((value,ci)=>{const col=startCol+ci;if(col===0)rows[target].client=value;if(col===1)rows[target].address=value;if(col===2)rows[target].attention=value;if(col===3)rows[target].active=boolFromPaste(value)})});return rows})}
 async function saveBatch(){const rows=batchRows.filter(r=>r.client.trim()||r.address.trim()||r.attention.trim());if(!rows.length)return setMsg('Paste at least one batch row.');const invalid=rows.find(r=>!r.client.trim()||!r.attention.trim());if(invalid)return setMsg('Client and Attention are required for each batch row.');setBusy(true);try{const r=await fetch('/api/clients',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({batch:rows})}),j=await r.json();if(!r.ok)throw new Error(j.error||'Batch add failed');setBatchModal(false);setBatchRows(tenBatch());setMsg(`Batch saved: ${j.inserted||0} Attention added, ${j.skipped||0} duplicate(s) skipped.`);await load()}catch(e){setMsg(e instanceof Error?e.message:'Batch add failed')}finally{setBusy(false)}}

 function patchSales(id:string,key:keyof SalesPerson,v:unknown){setSales(old=>old.map(x=>x.id===id?{...x,[key]:v}:x));setDirtySales(old=>new Set(old).add(id))}
 function patchDirector(id:string,key:keyof Director,v:unknown){setDirectors(old=>old.map(x=>x.id===id?{...x,[key]:v}:x));setDirtyDirectors(old=>new Set(old).add(id))}
 async function saveEntity(entity:'sales'|'directors',row:SalesPerson|Director,method:'POST'|'PATCH'='PATCH'){const payload={...row};if(method==='POST')delete (payload as any).id;const r=await fetch('/api/database',{method,headers:{'content-type':'application/json'},body:JSON.stringify({entity,row:payload})}),j=await r.json();if(!r.ok)throw new Error(j.error||'Save failed');return j}
 async function saveSalesChanges(){const rows=sales.filter(x=>dirtySales.has(x.id));if(!rows.length)return setMsg('No Sales PIC changes to save.');setBusy(true);try{for(const row of rows)await saveEntity('sales',row);setMsg(`Saved ${rows.length} Sales PIC change(s).`);await load()}catch(e){setMsg(e instanceof Error?e.message:'Save failed')}finally{setBusy(false)}}
 function patchSalesDraft(i:number,key:keyof SalesDraftRow,value:string|boolean){setSalesDraft(rows=>rows.map((r,j)=>j===i?{...r,[key]:value}:r))}
 function addSalesRows(){const count=Math.min(100,Math.max(1,salesRowsToAdd));setSalesDraft(rows=>[...rows,...Array.from({length:count},()=>emptySales())].slice(0,100))}
 function removeSalesDraft(i:number){setSalesDraft(rows=>rows.length<=10?rows.map((r,j)=>j===i?emptySales():r):rows.filter((_,j)=>j!==i))}
 function pasteSales(e:ClipboardEvent<HTMLInputElement>,rowIndex:number,startCol:0|1|2){const raw=e.clipboardData.getData('text/plain');if(!raw.includes('\t')&&!raw.includes('\n'))return;e.preventDefault();const matrix=raw.replace(/\r/g,'').split('\n').filter((x,i,a)=>x||i<a.length-1).map(x=>x.split('\t'));setSalesDraft(current=>{const rows=current.map(x=>({...x}));while(rows.length<Math.min(100,rowIndex+matrix.length))rows.push(emptySales());matrix.forEach((line,ri)=>{const target=rowIndex+ri;if(target>=100)return;line.forEach((value,ci)=>{const col=startCol+ci;if(col===0)rows[target].name=value;if(col===1)rows[target].email=value;if(col===2)rows[target].phone=value;if(col===3)rows[target].active=boolFromPaste(value)})});return rows})}
 async function addSales(){const rows=salesDraft.filter(r=>r.name.trim()||r.email.trim()||r.phone.trim());if(!rows.length)return setMsg('Fill at least one Sales PIC row.');const invalid=rows.find(r=>!r.name.trim()||!r.email.trim()||!r.phone.trim());if(invalid)return setMsg('Name, Email, and Phone are required for every Sales PIC row.');setBusy(true);try{for(const row of rows.sort((a,b)=>alpha(a.name,b.name)))await saveEntity('sales',{id:'',name:row.name.trim(),email:row.email.trim(),phone:row.phone.trim(),active:row.active},'POST');setSalesModal(false);setSalesDraft(tenSales());setMsg(`${rows.length} Sales PIC added.`);await load()}catch(e){setMsg(e instanceof Error?e.message:'Failed to add Sales PIC')}finally{setBusy(false)}}
 async function saveDirectorChanges(){const rows=directors.filter(x=>dirtyDirectors.has(x.id));if(!rows.length)return setMsg('No signatory changes to save.');setBusy(true);try{for(const row of rows)await saveEntity('directors',row);setMsg(`Saved ${rows.length} signatory change(s).`);await load()}catch(e){setMsg(e instanceof Error?e.message:'Save failed')}finally{setBusy(false)}}
 async function deleteEntity(entity:'sales'|'directors',id:string){if(!confirm('Delete this row?'))return;const r=await fetch('/api/database',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({entity,id})});if(!r.ok)return setMsg('Delete failed');await load()}

 return <>
  <LoadingOverlay show={loading||busy} label={busy?'Saving data...':'Loading Master Data...'}/>
  <header className="page-head"><div><h1>Master Data</h1><p>Manage Client Data, Sales PIC, and signatory data used by Create Quotation.</p></div></header>
  {msg&&<div className="notice">{msg}</div>}

  <section className="panel db-section">
   <div className="panel-title"><div><h2>Client Data</h2><p>Client and Address are stored once. Attention can be added individually or in batch.</p></div><div className="client-toolbar"><div className="member-search"><UiIcon name="search"/><input placeholder="Search client / attention" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div><button className="btn ghost" onClick={()=>{setBatchRows(tenBatch());setBatchRowsToAdd(10);setBatchModal(true)}}>Batch Add</button><button className="btn primary" onClick={openNewClient}>+ Add Client</button></div></div>
   <div className="history-wrap"><table className="db-table master-grid client-group-table zebra-grid"><thead><tr><th className="rowno">No</th><th>Client</th><th>Address</th><th>Attention</th><th>Active</th><th>Action</th></tr></thead><tbody>{paged.length?paged.map((c,i)=><tr key={c.client}><td className="rowno">{(safePage-1)*pageSize+i+1}</td><td>{c.client}</td><td className="client-address-cell">{c.address||''}</td><td>{c.attentions.filter(a=>a.active).length}</td><td className="active-cell"><input type="checkbox" checked={c.attentions.some(a=>a.active)} readOnly aria-label={`${c.client} active`}/></td><td className="client-actions"><button className="icon-only-button" title="Edit client" aria-label={`Edit ${c.client}`} onClick={()=>openEditClient(c)}><UiIcon name="edit" size={16}/></button><button className="x-button" title="Delete client" onClick={()=>deleteClient(c)}><UiIcon name="remove" size={15}/></button></td></tr>):<tr><td colSpan={6} className="empty-table">No Client Data found.</td></tr>}</tbody></table></div>
   <PaginationBar page={safePage} pageSize={pageSize} total={filtered.length} onPageChange={setPage} onPageSizeChange={s=>{setPageSize(s);setPage(1)}}/>
  </section>

  <section className="panel db-section"><div className="panel-title"><div><h2>Sales PIC</h2><p>Sorted automatically by Name. Maximum 10 rows are visible before scrolling.</p></div><div className="table-actions"><button className="btn ghost" onClick={()=>{setSalesDraft(tenSales());setSalesRowsToAdd(10);setSalesModal(true)}}>+ Add PIC</button><button className="btn primary" disabled={busy} onClick={saveSalesChanges}>Save Changes</button></div></div><div className="sales-scroll"><table className="db-table master-grid compact-db zebra-grid"><thead><tr><th className="rowno">No</th><th>Name</th><th>Email</th><th>Phone</th><th>Active</th><th>Action</th></tr></thead><tbody>{sales.map((row,i)=><tr key={row.id}><td className="rowno">{i+1}</td><td><input value={row.name||''} onChange={e=>patchSales(row.id,'name',e.target.value)}/></td><td><input value={row.email||''} onChange={e=>patchSales(row.id,'email',e.target.value)}/></td><td><input value={row.phone||''} onChange={e=>patchSales(row.id,'phone',e.target.value)}/></td><td className="active-cell"><input type="checkbox" checked={row.active!==false} onChange={e=>patchSales(row.id,'active',e.target.checked)}/></td><td><button className="x-button" title="Delete Sales PIC" onClick={()=>deleteEntity('sales',row.id)}><UiIcon name="remove" size={15}/></button></td></tr>)}</tbody></table></div></section>

  <section className="panel signatory-section"><div className="panel-title"><div><h2>President Director</h2><p>All fields remain editable.</p></div><button className="btn primary" disabled={busy} onClick={saveDirectorChanges}>Save Changes</button></div><div className="signatory-layout"><div className="history-wrap"><table className="db-table master-grid compact-db zebra-grid"><thead><tr><th>Name</th><th>Title</th><th>Active</th><th>Action</th></tr></thead><tbody>{directors.map(row=><tr key={row.id}><td><input value={row.name||''} onChange={e=>patchDirector(row.id,'name',e.target.value)}/></td><td><input value={row.title||''} onChange={e=>patchDirector(row.id,'title',e.target.value)}/></td><td className="active-cell"><input type="checkbox" checked={row.active!==false} onChange={e=>patchDirector(row.id,'active',e.target.checked)}/></td><td><button className="x-button" title="Delete signatory" onClick={()=>deleteEntity('directors',row.id)}><UiIcon name="remove" size={15}/></button></td></tr>)}</tbody></table></div><div className="signature-preview"><span>Signature Preview</span><img src="/signature-mr-herry.png" alt="President Director signature"/></div></div></section>

  {clientModal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setClientModal(false)}}><div className="modal-card client-modal"><div className="modal-head"><div><h2>{originalClient?'Edit Client':'Add Client'}</h2><p>Client and Address are entered once. Add or paste Attention rows below.</p></div><button className="x-button" onClick={()=>setClientModal(false)}><UiIcon name="remove"/></button></div><div className="modal-fields"><label>Client<input value={draftClient.client} onChange={e=>matchExistingClient(e.target.value)} placeholder="Client name"/></label><label>Address<textarea rows={3} value={draftClient.address||''} onChange={e=>setDraftClient(d=>({...d,address:e.target.value}))} placeholder="Client address"/></label></div><div className="attention-head"><div><h3>Attention</h3><small>{draftClient.attentions.length}/100 rows</small></div><div className="add-many"><input aria-label="Attention rows to add" type="number" min="1" max="100" value={attentionRowsToAdd} onChange={e=>setAttentionRowsToAdd(Math.min(100,Math.max(1,Number(e.target.value)||10)))}/><button className="btn ghost small" onClick={addAttentionRows} disabled={draftClient.attentions.length>=100}>+ Add Rows</button></div></div><div className="attention-scroll"><table className="db-table master-grid editable-grid zebra-grid"><thead><tr><th className="rowno">No</th><th>Attention</th><th>Active</th><th>Action</th></tr></thead><tbody>{draftClient.attentions.map((a,i)=><tr key={a.id||i}><td className="rowno">{i+1}</td><td><input value={a.name} onPaste={e=>pasteAttention(e,i,0)} onChange={e=>patchAttention(i,'name',e.target.value)}/></td><td className="active-cell"><input type="checkbox" checked={a.active} onChange={e=>patchAttention(i,'active',e.target.checked)}/></td><td><button className="x-button" onClick={()=>removeAttention(i)}><UiIcon name="remove" size={14}/></button></td></tr>)}</tbody></table></div><div className="modal-actions"><button className="btn ghost" onClick={()=>setClientModal(false)}>Cancel</button><button className="btn primary" disabled={busy} onClick={saveClient}>{busy?'Saving...':'Save Client'}</button></div></div></div>}

  {batchModal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setBatchModal(false)}}><div className="modal-card batch-client-modal"><div className="modal-head"><div><h2>Batch Add Client Data</h2><p>Paste Client, Address, and Attention from Excel. Repeated Client + Address values are stored as one client; duplicate Attention names are skipped.</p></div><button className="x-button" onClick={()=>setBatchModal(false)}><UiIcon name="remove"/></button></div><div className="attention-head"><div><h3>Client rows</h3><small>{batchRows.length}/500 rows</small></div><div className="add-many"><input aria-label="Batch client rows to add" type="number" min="1" max="500" value={batchRowsToAdd} onChange={e=>setBatchRowsToAdd(Math.min(500,Math.max(1,Number(e.target.value)||10)))}/><button className="btn ghost small" onClick={addBatchRows}>+ Add Rows</button></div></div><div className="batch-scroll"><table className="db-table master-grid editable-grid zebra-grid"><thead><tr><th className="rowno">No</th><th>Client</th><th>Address</th><th>Attention</th><th>Active</th><th>Action</th></tr></thead><tbody>{batchRows.map((row,i)=><tr key={i}><td className="rowno">{i+1}</td><td><input value={row.client} onPaste={e=>pasteBatch(e,i,0)} onChange={e=>patchBatch(i,'client',e.target.value)}/></td><td><input value={row.address} onPaste={e=>pasteBatch(e,i,1)} onChange={e=>patchBatch(i,'address',e.target.value)}/></td><td><input value={row.attention} onPaste={e=>pasteBatch(e,i,2)} onChange={e=>patchBatch(i,'attention',e.target.value)}/></td><td className="active-cell"><input type="checkbox" checked={row.active} onChange={e=>patchBatch(i,'active',e.target.checked)}/></td><td><button className="x-button" onClick={()=>removeBatchRow(i)}><UiIcon name="remove" size={14}/></button></td></tr>)}</tbody></table></div><div className="modal-actions"><button className="btn ghost" onClick={()=>setBatchModal(false)}>Cancel</button><button className="btn primary" disabled={busy} onClick={saveBatch}>{busy?'Saving...':'Save Batch'}</button></div></div></div>}

  {salesModal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSalesModal(false)}}><div className="modal-card"><div className="modal-head"><div><h2>Add Sales PIC</h2><p>Default 10 rows. Paste Name, Email, and Phone directly from Excel.</p></div><button className="x-button" onClick={()=>setSalesModal(false)}><UiIcon name="remove"/></button></div><div className="attention-head"><div><h3>Sales PIC rows</h3><small>{salesDraft.length}/100 rows</small></div><div className="add-many"><input aria-label="Sales rows to add" type="number" min="1" max="100" value={salesRowsToAdd} onChange={e=>setSalesRowsToAdd(Math.min(100,Math.max(1,Number(e.target.value)||10)))}/><button className="btn ghost small" onClick={addSalesRows}>+ Add Rows</button></div></div><div className="attention-scroll"><table className="db-table master-grid editable-grid zebra-grid"><thead><tr><th className="rowno">No</th><th>Name</th><th>Email</th><th>Phone</th><th>Active</th><th>Action</th></tr></thead><tbody>{salesDraft.map((row,i)=><tr key={i}><td className="rowno">{i+1}</td><td><input value={row.name} onPaste={e=>pasteSales(e,i,0)} onChange={e=>patchSalesDraft(i,'name',e.target.value)}/></td><td><input value={row.email} onPaste={e=>pasteSales(e,i,1)} onChange={e=>patchSalesDraft(i,'email',e.target.value)}/></td><td><input value={row.phone} onPaste={e=>pasteSales(e,i,2)} onChange={e=>patchSalesDraft(i,'phone',e.target.value)}/></td><td className="active-cell"><input type="checkbox" checked={row.active} onChange={e=>patchSalesDraft(i,'active',e.target.checked)}/></td><td><button className="x-button" onClick={()=>removeSalesDraft(i)}><UiIcon name="remove" size={14}/></button></td></tr>)}</tbody></table></div><div className="modal-actions"><button className="btn ghost" onClick={()=>setSalesModal(false)}>Cancel</button><button className="btn primary" disabled={busy} onClick={addSales}>{busy?'Adding...':'Add Sales PIC'}</button></div></div></div>}
 </>
}
