'use client';
import {useEffect,useMemo,useState} from 'react';
import type {Director,SalesPerson} from '@/lib/types';
import UiIcon from './UiIcon';
import PaginationBar from './PaginationBar';

type AttentionRow={id?:string;name:string;address:string;active:boolean};
type ClientGroup={client:string;code:string;active:boolean;attentions:AttentionRow[]};
const alpha=(a:string,b:string)=>a.localeCompare(b,undefined,{sensitivity:'base'});
const emptyAttention=():AttentionRow=>({name:'',address:'',active:true});

export default function DatabaseApp(){
 const [clients,setClients]=useState<ClientGroup[]>([]),[sales,setSales]=useState<SalesPerson[]>([]),[directors,setDirectors]=useState<Director[]>([]);
 const [search,setSearch]=useState(''),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(25),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const [clientModal,setClientModal]=useState(false),[originalClient,setOriginalClient]=useState(''),[draftClient,setDraftClient]=useState<ClientGroup>({client:'',code:'',active:true,attentions:[emptyAttention()]});
 const [salesModal,setSalesModal]=useState(false),[salesDraft,setSalesDraft]=useState({name:'',email:'',phone:''});
 const [dirtySales,setDirtySales]=useState<Set<string>>(new Set()),[dirtyDirectors,setDirtyDirectors]=useState<Set<string>>(new Set());

 async function load(){
  setBusy(true);try{
   const [cr,mr]=await Promise.all([fetch('/api/clients',{cache:'no-store'}),fetch('/api/masters',{cache:'no-store'})]);
   const [cj,mj]=await Promise.all([cr.json(),mr.json()]);if(!cr.ok)throw new Error(cj.error||'Failed to load Client Data');if(!mr.ok)throw new Error(mj.error||'Failed to load master data');
   setClients((cj||[]).sort((a:ClientGroup,b:ClientGroup)=>alpha(a.client,b.client)));setSales((mj.sales||[]).sort((a:SalesPerson,b:SalesPerson)=>alpha(a.name,b.name)));setDirectors((mj.directors||[]).sort((a:Director,b:Director)=>alpha(a.name,b.name)));setDirtySales(new Set());setDirtyDirectors(new Set());
  }catch(e){setMsg(e instanceof Error?e.message:'Failed to load Master Data')}finally{setBusy(false)}
 }
 useEffect(()=>{void load()},[]);

 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return clients.filter(c=>!q||[c.client,c.code,...c.attentions.flatMap(a=>[a.name,a.address])].join(' ').toLowerCase().includes(q))},[clients,search]);
 const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)),safePage=Math.min(page,totalPages),paged=filtered.slice((safePage-1)*pageSize,safePage*pageSize);
 useEffect(()=>{if(page>totalPages)setPage(totalPages)},[page,totalPages]);

 function openNewClient(){setOriginalClient('');setDraftClient({client:'',code:'',active:true,attentions:[emptyAttention()]});setClientModal(true)}
 function openEditClient(c:ClientGroup){setOriginalClient(c.client);setDraftClient({client:c.client,code:c.code,active:c.active,attentions:c.attentions.map(a=>({...a}))});setClientModal(true)}
 function matchExistingClient(name:string){const found=clients.find(c=>c.client.trim().toLowerCase()===name.trim().toLowerCase());if(found&&!originalClient){setOriginalClient(found.client);setDraftClient({client:found.client,code:found.code,active:found.active,attentions:found.attentions.map(a=>({...a}))})}else setDraftClient(d=>({...d,client:name}))}
 function patchAttention(i:number,key:keyof AttentionRow,v:string|boolean){setDraftClient(d=>({...d,attentions:d.attentions.map((a,j)=>j===i?{...a,[key]:v}:a)}))}
 function addAttention(){if(draftClient.attentions.length>=100)return;setDraftClient(d=>({...d,attentions:[...d.attentions,emptyAttention()]}))}
 function removeAttention(i:number){setDraftClient(d=>({...d,attentions:d.attentions.length===1?[emptyAttention()]:d.attentions.filter((_,j)=>j!==i)}))}
 async function saveClient(){setBusy(true);setMsg('');try{const method=originalClient?'PATCH':'POST';const payload={...draftClient,originalClient:originalClient||undefined,attentions:draftClient.attentions.filter(a=>a.name.trim()).sort((a,b)=>alpha(a.name,b.name))};const r=await fetch('/api/clients',{method,headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok)throw new Error(j.error||'Failed to save client');setClientModal(false);setMsg(`${draftClient.client} saved.`);await load()}catch(e){setMsg(e instanceof Error?e.message:'Failed to save client')}finally{setBusy(false)}}
 async function deleteClient(c:ClientGroup){if(!confirm(`Delete ${c.client} and all Attention data?`))return;const r=await fetch('/api/clients',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({client:c.client})}),j=await r.json();if(!r.ok)return setMsg(j.error||'Delete failed');setMsg(`${c.client} deleted.`);await load()}

 function patchSales(id:string,key:keyof SalesPerson,v:unknown){setSales(old=>old.map(x=>x.id===id?{...x,[key]:v}:x));setDirtySales(old=>new Set(old).add(id))}
 function patchDirector(id:string,key:keyof Director,v:unknown){setDirectors(old=>old.map(x=>x.id===id?{...x,[key]:v}:x));setDirtyDirectors(old=>new Set(old).add(id))}
 async function saveEntity(entity:'sales'|'directors',row:SalesPerson|Director,method:'POST'|'PATCH'='PATCH'){const payload={...row};if(method==='POST')delete (payload as any).id;const r=await fetch('/api/database',{method,headers:{'content-type':'application/json'},body:JSON.stringify({entity,row:payload})}),j=await r.json();if(!r.ok)throw new Error(j.error||'Save failed');return j}
 async function saveSalesChanges(){const rows=sales.filter(x=>dirtySales.has(x.id));if(!rows.length)return setMsg('No Sales PIC changes to save.');setBusy(true);try{for(const row of rows)await saveEntity('sales',row);setMsg(`Saved ${rows.length} Sales PIC change(s).`);await load()}catch(e){setMsg(e instanceof Error?e.message:'Save failed')}finally{setBusy(false)}}
 async function addSales(){if(!salesDraft.name.trim()||!salesDraft.email.trim()||!salesDraft.phone.trim())return setMsg('Name, Email, and Phone are required.');setBusy(true);try{await saveEntity('sales',{id:'',name:salesDraft.name.trim(),email:salesDraft.email.trim(),phone:salesDraft.phone.trim(),active:true},'POST');setSalesModal(false);setSalesDraft({name:'',email:'',phone:''});setMsg('Sales PIC added.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Failed to add Sales PIC')}finally{setBusy(false)}}
 async function saveDirectorChanges(){const rows=directors.filter(x=>dirtyDirectors.has(x.id));if(!rows.length)return setMsg('No signatory changes to save.');setBusy(true);try{for(const row of rows)await saveEntity('directors',row);setMsg(`Saved ${rows.length} signatory change(s).`);await load()}catch(e){setMsg(e instanceof Error?e.message:'Save failed')}finally{setBusy(false)}}
 async function deleteEntity(entity:'sales'|'directors',id:string){if(!confirm('Delete this row?'))return;const r=await fetch('/api/database',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({entity,id})});if(!r.ok)return setMsg('Delete failed');await load()}

 return <>
  <header className="page-head"><div><h1>Master Data</h1><p>Manage Client Data, Sales PIC, and signatory data used by Create Quotation.</p></div></header>
  {msg&&<div className="notice">{msg}</div>}

  <section className="panel db-section">
   <div className="panel-title"><div><h2>Client Data</h2><p>Client and Code are stored once. Each Client can have up to 100 Attention records.</p></div><div className="client-toolbar"><div className="member-search"><UiIcon name="search"/><input placeholder="Search client / attention" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></div><button className="btn primary" onClick={openNewClient}>+ Add Client</button></div></div>
   <div className="history-wrap"><table className="db-table client-group-table zebra-grid"><thead><tr><th className="rowno">No</th><th>Client</th><th>Code</th><th>Attention</th><th>Active</th><th>Action</th></tr></thead><tbody>{paged.length?paged.map((c,i)=><tr key={c.client}><td className="rowno">{(safePage-1)*pageSize+i+1}</td><td><b>{c.client}</b></td><td>{c.code}</td><td>{c.attentions.filter(a=>a.active).length}</td><td>{c.attentions.some(a=>a.active)?'Yes':'No'}</td><td className="client-actions"><button className="btn ghost small" onClick={()=>openEditClient(c)}>Edit</button><button className="x-button" title="Delete client" onClick={()=>deleteClient(c)}><UiIcon name="remove" size={15}/></button></td></tr>):<tr><td colSpan={6} className="empty-table">No Client Data found.</td></tr>}</tbody></table></div>
   <PaginationBar page={safePage} pageSize={pageSize} total={filtered.length} onPageChange={setPage} onPageSizeChange={s=>{setPageSize(s);setPage(1)}}/>
  </section>

  <section className="panel db-section"><div className="panel-title"><div><h2>Sales PIC</h2><p>Sorted automatically by Name. Maximum 10 rows are visible before scrolling.</p></div><div className="table-actions"><button className="btn ghost" onClick={()=>setSalesModal(true)}>+ Add PIC</button><button className="btn primary" disabled={busy} onClick={saveSalesChanges}>Save Changes</button></div></div><div className="sales-scroll"><table className="db-table compact-db zebra-grid"><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Active</th><th></th></tr></thead><tbody>{sales.map(row=><tr key={row.id}><td><input value={row.name||''} onChange={e=>patchSales(row.id,'name',e.target.value)}/></td><td><input value={row.email||''} onChange={e=>patchSales(row.id,'email',e.target.value)}/></td><td><input value={row.phone||''} onChange={e=>patchSales(row.id,'phone',e.target.value)}/></td><td><input type="checkbox" checked={row.active!==false} onChange={e=>patchSales(row.id,'active',e.target.checked)}/></td><td><button className="x-button" title="Delete Sales PIC" onClick={()=>deleteEntity('sales',row.id)}><UiIcon name="remove" size={15}/></button></td></tr>)}</tbody></table></div></section>

  <section className="panel signatory-section"><div className="panel-title"><div><h2>President Director</h2><p>All fields remain editable. Signature is embedded in GitHub at <code>/public/signature-mr-herry.png</code>.</p></div><button className="btn primary" disabled={busy} onClick={saveDirectorChanges}>Save Changes</button></div><div className="signatory-layout"><div className="history-wrap"><table className="db-table compact-db zebra-grid"><thead><tr><th>Name</th><th>Title</th><th>Active</th><th></th></tr></thead><tbody>{directors.map(row=><tr key={row.id}><td><input value={row.name||''} onChange={e=>patchDirector(row.id,'name',e.target.value)}/></td><td><input value={row.title||''} onChange={e=>patchDirector(row.id,'title',e.target.value)}/></td><td><input type="checkbox" checked={row.active!==false} onChange={e=>patchDirector(row.id,'active',e.target.checked)}/></td><td><button className="x-button" title="Delete signatory" onClick={()=>deleteEntity('directors',row.id)}><UiIcon name="remove" size={15}/></button></td></tr>)}</tbody></table></div><div className="signature-preview"><span>Embedded Signature</span><img src="/signature-mr-herry.png" alt="President Director signature"/></div></div></section>

  {clientModal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setClientModal(false)}}><div className="modal-card client-modal"><div className="modal-head"><div><h2>{originalClient?'Edit Client':'Add Client'}</h2><p>Client and Code only need to be entered once.</p></div><button className="x-button" onClick={()=>setClientModal(false)}><UiIcon name="remove"/></button></div><div className="modal-fields two"><label>Client<input value={draftClient.client} onChange={e=>matchExistingClient(e.target.value)} placeholder="Client name"/></label><label>Code<input value={draftClient.code} onChange={e=>setDraftClient(d=>({...d,code:e.target.value.toUpperCase()}))} placeholder="e.g. KCC"/></label></div><div className="attention-head"><div><h3>Attention</h3><small>{draftClient.attentions.length}/100 rows</small></div><button className="btn ghost small" onClick={addAttention} disabled={draftClient.attentions.length>=100}>+ Add Attention</button></div><div className="attention-scroll"><table className="db-table editable-grid zebra-grid"><thead><tr><th className="rowno">No</th><th>Attention</th><th>Address</th><th>Active</th><th></th></tr></thead><tbody>{draftClient.attentions.map((a,i)=><tr key={a.id||i}><td className="rowno">{i+1}</td><td><input value={a.name} onChange={e=>patchAttention(i,'name',e.target.value)}/></td><td><input value={a.address} onChange={e=>patchAttention(i,'address',e.target.value)}/></td><td><input type="checkbox" checked={a.active} onChange={e=>patchAttention(i,'active',e.target.checked)}/></td><td><button className="x-button" onClick={()=>removeAttention(i)}><UiIcon name="remove" size={14}/></button></td></tr>)}</tbody></table></div><div className="modal-actions"><button className="btn ghost" onClick={()=>setClientModal(false)}>Cancel</button><button className="btn primary" disabled={busy} onClick={saveClient}>{busy?'Saving...':'Save Client'}</button></div></div></div>}

  {salesModal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSalesModal(false)}}><div className="modal-card sales-modal"><div className="modal-head"><div><h2>Add Sales PIC</h2><p>Fill Name, Email, and Phone, then click Add.</p></div><button className="x-button" onClick={()=>setSalesModal(false)}><UiIcon name="remove"/></button></div><div className="modal-fields"><label>Name<input value={salesDraft.name} onChange={e=>setSalesDraft(d=>({...d,name:e.target.value}))}/></label><label>Email<input type="email" value={salesDraft.email} onChange={e=>setSalesDraft(d=>({...d,email:e.target.value}))}/></label><label>Phone<input value={salesDraft.phone} onChange={e=>setSalesDraft(d=>({...d,phone:e.target.value}))}/></label></div><div className="modal-actions"><button className="btn ghost" onClick={()=>setSalesModal(false)}>Cancel</button><button className="btn primary" disabled={busy} onClick={addSales}>{busy?'Adding...':'Add'}</button></div></div></div>}
 </>
}
