'use client';
import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import MultiCheckFilter from './MultiCheckFilter';
import UiIcon from './UiIcon';
import PaginationBar from './PaginationBar';
import SearchPopover from './SearchPopover';
import LoadingOverlay from './LoadingOverlay';
import type {QuoteItem,StoredQuotation} from '@/lib/types';

const idr=new Intl.NumberFormat('id-ID');
type HistoryItemRow={quote:StoredQuotation;item:QuoteItem|null;itemIndex:number;groupIndex:number;rowSpan:number};

export default function HistoryApp(){
 const router=useRouter();
 const [rows,setRows]=useState<StoredQuotation[]>([]),[search,setSearch]=useState(''),[appliedSearch,setAppliedSearch]=useState(''),[sales,setSales]=useState<string[]>([]),[clients,setClients]=useState<string[]>([]),[loading,setLoading]=useState(true),[loadingLabel,setLoadingLabel]=useState('Loading Quotation List...'),[msg,setMsg]=useState('');
 const [page,setPage]=useState(1),[pageSize,setPageSize]=useState(25),[selectedIds,setSelectedIds]=useState<Set<string>>(new Set());
 async function load(){setLoadingLabel('Loading Quotation List...');setLoading(true);try{const r=await fetch('/api/history',{cache:'no-store'}),j=await r.json();if(r.ok)setRows(j);else setMsg(j.error||'Failed to load')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const searchTerms=useMemo(()=>appliedSearch.split(/\r?\n/).map(x=>x.trim().toLowerCase()).filter(Boolean),[appliedSearch]);
 const passSearch=(r:StoredQuotation)=>{if(!searchTerms.length)return true;const blob=[r.quotation_no,r.quotation_date,r.client_name,r.sales_name,r.total_amount,r.content?.attention,r.content?.address,r.content?.rfqNo,...(r.content?.items||[]).flatMap(i=>[i.productName,i.spec,i.brand,i.user,i.leadTime,i.qty,i.uom,i.unitPrice,(i.qty||0)*(i.unitPrice||0),i.remarks]),...(r.content?.notes||[])].join(' ').toLowerCase();return searchTerms.some(t=>blob.includes(t))};
 const baseForSales=useMemo(()=>rows.filter(r=>passSearch(r)&&(clients.length===0||clients.includes(r.client_name))),[rows,searchTerms.join('|'),clients.join('|')]);
 const baseForClients=useMemo(()=>rows.filter(r=>passSearch(r)&&(sales.length===0||sales.includes(r.sales_name))),[rows,searchTerms.join('|'),sales.join('|')]);
 const salesOptions=useMemo<string[]>(()=>[...new Set<string>(baseForSales.map(r=>String(r.sales_name||'')).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{sensitivity:'base'})),[baseForSales]);
 const clientOptions=useMemo<string[]>(()=>[...new Set<string>(baseForClients.map(r=>String(r.client_name||'')).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{sensitivity:'base'})),[baseForClients]);
 const filtered=useMemo(()=>rows.filter(r=>passSearch(r)&&(sales.length===0||sales.includes(r.sales_name))&&(clients.length===0||clients.includes(r.client_name))),[rows,searchTerms.join('|'),sales.join('|'),clients.join('|')]);
 const summary=useMemo(()=>({quotes:filtered.length,amount:filtered.reduce((sum,r)=>sum+(r.content?.items||[]).reduce((s,item)=>s+(Number(item.qty)||0)*(Number(item.unitPrice)||0),0),0),clients:new Set(filtered.map(r=>r.client_name).filter(Boolean)).size}),[filtered]);
 const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)),safePage=Math.min(page,totalPages),pageQuotes=filtered.slice((safePage-1)*pageSize,safePage*pageSize);
 const tableRows=useMemo(()=>pageQuotes.flatMap<HistoryItemRow>((quote,groupIndex)=>{const items=quote.content?.items?.length?quote.content.items:[null];return items.map((item,itemIndex)=>({quote,item,itemIndex,groupIndex,rowSpan:items.length}))}),[pageQuotes]);
 const selectedQuotes=useMemo(()=>filtered.filter(q=>selectedIds.has(q.id)),[filtered,selectedIds]);
 const pageIds=useMemo(()=>pageQuotes.map(q=>q.id),[pageQuotes]);
 const allPageSelected=pageIds.length>0&&pageIds.every(id=>selectedIds.has(id));
 useEffect(()=>{if(page>totalPages)setPage(totalPages)},[page,totalPages]);
 useEffect(()=>{const allowed=new Set(filtered.map(q=>q.id));setSelectedIds(current=>{const next=new Set([...current].filter(id=>allowed.has(id)));return next.size===current.size&&[...next].every(id=>current.has(id))?current:next})},[filtered]);
 async function download(){setMsg('');setLoadingLabel('Preparing Excel...');setLoading(true);try{const r=await fetch('/api/history/export',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ids:filtered.map(x=>x.id)})});if(!r.ok)return setMsg(await r.text());const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='quotation-list.xlsx';a.click();URL.revokeObjectURL(u)}finally{setLoading(false)}}
 async function deleteSelected(){if(!selectedQuotes.length)return;const names=selectedQuotes.slice(0,5).map(q=>q.quotation_no).join('\n');const more=selectedQuotes.length>5?`\n...and ${selectedQuotes.length-5} more`:'';if(!confirm(`Delete ${selectedQuotes.length} selected quotation(s)?\n\n${names}${more}\n\nDeleted quotation numbers will NOT be reused.`))return;setMsg('');setLoadingLabel('Deleting selected quotations...');setLoading(true);try{const r=await fetch('/api/history/batch',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({ids:selectedQuotes.map(q=>q.id)})});const j=await r.json().catch(()=>({}));if(!r.ok)return setMsg(j.error||'Failed to delete selected quotations');const deleted=new Set(selectedQuotes.map(q=>q.id));setRows(current=>current.filter(q=>!deleted.has(q.id)));setSelectedIds(new Set());setMsg(`${selectedQuotes.length} quotation(s) deleted. Running numbers remain reserved.`)}finally{setLoading(false)}}
 async function printSelected(){if(!selectedQuotes.length)return;setMsg('');setLoadingLabel('Preparing selected quotations...');setLoading(true);try{const r=await fetch('/api/history/print',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ids:selectedQuotes.map(q=>q.id)})});if(!r.ok)return setMsg(await r.text());const b=await r.blob(),u=URL.createObjectURL(b);const w=window.open(u,'_blank');if(w)w.opener=null;else{const a=document.createElement('a');a.href=u;a.download='selected-quotations.pdf';a.click()}setTimeout(()=>URL.revokeObjectURL(u),60000)}finally{setLoading(false)}}
 const clear=()=>{setSales([]);setClients([]);setSearch('');setAppliedSearch('');setPage(1)};
 const applySearch=()=>{setAppliedSearch(search);setPage(1)};
 const toggleSelected=(id:string)=>setSelectedIds(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next});
 const togglePage=()=>setSelectedIds(current=>{const next=new Set(current);if(allPageSelected)pageIds.forEach(id=>next.delete(id));else pageIds.forEach(id=>next.add(id));return next});
 return <>
 <LoadingOverlay show={loading} label={loadingLabel}/>
 <header className="page-head"><div><h1>Quotation List</h1><p>Search, filter, reload, print, or delete quotation records.</p></div><div className="head-actions"><button className="btn ghost icon-btn" onClick={load}><UiIcon name="refresh"/>Refresh</button></div></header>{msg&&<div className="notice">{msg}</div>}
 <section className="summary-grid"><div><small>Clients</small><b>{summary.clients}</b></div><div><small>Quotes</small><b>{summary.quotes}</b></div><div><small>Amount</small><b>IDR {idr.format(summary.amount)}</b></div></section>
 <section className="panel"><div className="list-tools aligned-list-tools"><div className="filters toolbar-row"><SearchPopover value={search} onChange={setSearch} onSearch={applySearch} onClear={()=>{setSearch('');setAppliedSearch('');setPage(1)}}/><MultiCheckFilter label="Sales PIC" values={salesOptions} selected={sales} onChange={v=>{setSales(v);setPage(1)}}/><MultiCheckFilter label="Client" values={clientOptions} selected={clients} onChange={v=>{setClients(v);setPage(1)}}/>{(sales.length||clients.length||appliedSearch)&&<button className="btn ghost toolbar-btn" onClick={clear}>Clear Filters</button>}<div className="list-toolbar-spacer"/><button className="icon-only-button danger-action" title="Delete selected" aria-label="Delete selected quotations" disabled={!selectedQuotes.length} onClick={()=>void deleteSelected()}><UiIcon name="trash" size={18}/></button><button className="icon-only-button" title="Print selected" aria-label="Print selected quotations" disabled={!selectedQuotes.length} onClick={()=>void printSelected()}><UiIcon name="print" size={18}/></button><button className="btn excel icon-btn list-download" onClick={download}><UiIcon name="download"/>Download Excel</button></div></div>
 <div className="history-wrap quotation-sheet-wrap"><table className="history-table item-history quotation-sheet selection-history"><thead><tr><th className="select-col"><input type="checkbox" aria-label="Select quotations on this page" checked={allPageSelected} onChange={togglePage}/></th><th className="reload-col">Reload</th><th className="rowno">No</th><th>Quotation No.</th><th>Date</th><th>Client</th><th>Sales PIC</th><th className="rowno">Item No</th><th>Item / Description</th><th>Specification</th><th>Brand</th><th>User</th><th>Lead Time (Days)</th><th>Qty</th><th>UOM</th><th>Unit Price</th><th>Amount</th><th>Remarks</th></tr></thead><tbody>{tableRows.length?tableRows.map(({quote,item,itemIndex,groupIndex,rowSpan})=>{const first=itemIndex===0;return <tr key={`${quote.id}-${itemIndex}`} className={`${groupIndex%2?'quote-group-alt':'quote-group-base'} ${first?'quote-group-start':''}`}>
 {first&&<><td className="select-col merged-cell" rowSpan={rowSpan}><input type="checkbox" aria-label={`Select ${quote.quotation_no}`} checked={selectedIds.has(quote.id)} onChange={()=>toggleSelected(quote.id)}/></td><td className="reload-col merged-cell" rowSpan={rowSpan}><button className="icon-only-button reload-icon" title="Muat Ulang" aria-label={`Muat Ulang ${quote.quotation_no}`} onClick={()=>router.push(`/?reload=${quote.id}`)}><UiIcon name="refresh" size={16}/></button></td><td className="rowno merged-cell" rowSpan={rowSpan}>{(safePage-1)*pageSize+groupIndex+1}</td><td className="merged-cell" rowSpan={rowSpan}><b>{quote.quotation_no}</b></td><td className="merged-cell" rowSpan={rowSpan}>{quote.quotation_date}</td><td className="merged-cell" rowSpan={rowSpan}>{quote.client_name}</td><td className="merged-cell" rowSpan={rowSpan}>{quote.sales_name}</td></>}
 <td className="rowno">{itemIndex+1}</td><td>{item?.productName||''}</td><td>{item?.spec||''}</td><td>{item?.brand||''}</td><td>{item?.user||''}</td><td className="center-cell">{item?.leadTime||''}</td><td className="num">{item?.qty||''}</td><td className="center-cell">{item?.uom||''}</td><td className="num">{item?`IDR ${idr.format(item.unitPrice||0)}`:''}</td><td className="num">{item?`IDR ${idr.format((item.qty||0)*(item.unitPrice||0))}`:''}</td><td className="history-remark readonly-remark">{item?.remarks||''}</td>
 </tr>}) :<tr><td colSpan={18} className="empty-table">No quotation matches the current filters.</td></tr>}</tbody></table></div>
 <PaginationBar page={safePage} pageSize={pageSize} total={filtered.length} onPageChange={setPage} onPageSizeChange={size=>{setPageSize(size);setPage(1)}}/>
 </section></>
}
