'use client';
import {useEffect,useMemo,useState} from 'react';
import {useSearchParams,useRouter} from 'next/navigation';
import {SearchSelect} from './SearchSelect';
import SpreadsheetGrid,{blankRow} from './SpreadsheetGrid';
import type {Director,MemberRecord,QuoteContent,QuoteItem,SalesPerson,StoredQuotation,Uom} from '@/lib/types';
import {COMPANY_ADDRESS,COMPANY_NAME} from '@/lib/constants';
import UiIcon from './UiIcon';
import LoadingOverlay from './LoadingOverlay';
const todayJakarta=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta'}).format(new Date());
const tenRows=()=>Array.from({length:10},()=>blankRow());
const PREF_KEY='serveone-create-quotation-preferences';
const alpha=(a:string,b:string)=>a.localeCompare(b,undefined,{sensitivity:'base'});
type RequiredField='date'|'validity'|'sales'|'client'|'attention';
export default function QuotationApp(){
 const sp=useSearchParams(),router=useRouter();const reloadId=sp.get('reload');
 const [sales,setSales]=useState<SalesPerson[]>([]),[members,setMembers]=useState<MemberRecord[]>([]),[directors,setDirectors]=useState<Director[]>([]),[uoms,setUoms]=useState<Uom[]>([]);
 const [salesId,setSalesId]=useState(''),[clientId,setClientId]=useState(''),[clientName,setClientName]=useState('');
 const [attention,setAttention]=useState(''),[address,setAddress]=useState(''),[items,setItems]=useState<QuoteItem[]>(tenRows()),[notes,setNotes]=useState<string[]>(['Items price exclude VAT','Payment condition: 30 days after issue invoice','Lead time is available after PO issued to Serveone','Franco Jakarta']);
 const [date,setDate]=useState(todayJakarta()),[validity,setValidity]=useState(30),[vatRate,setVatRate]=useState(11),[rfq,setRfq]=useState('');
 const [companyAddress,setCompanyAddress]=useState(COMPANY_ADDRESS);
 const [quotationId,setQuotationId]=useState<string|null>(null),[quotationNo,setQuotationNo]=useState(''),[originalContent,setOriginalContent]=useState<QuoteContent|null>(null),[busy,setBusy]=useState<'excel'|'pdf'|null>(null),[msg,setMsg]=useState(''),[rowsToAdd,setRowsToAdd]=useState(10);
 const [masterLoading,setMasterLoading]=useState(true),[quoteLoading,setQuoteLoading]=useState(!!reloadId),[invalid,setInvalid]=useState<Set<RequiredField>>(new Set());
 useEffect(()=>{(async()=>{setMasterLoading(true);try{const r=await fetch('/api/masters',{cache:'no-store'});const j=await r.json();if(!r.ok)return setMsg(j.error||'Failed to load database');setSales((j.sales||[]).sort((a:SalesPerson,b:SalesPerson)=>alpha(a.name,b.name)));setMembers(j.members||[]);setDirectors(j.directors||[]);setUoms(j.uoms||[]);if(reloadId)return;setCompanyAddress(String(j.companyAddress||COMPANY_ADDRESS));let saved:{salesId?:string;vatRate?:number}={};try{saved=JSON.parse(localStorage.getItem(PREF_KEY)||'{}')}catch{}if(Number.isFinite(Number(saved.vatRate)))setVatRate(Number(saved.vatRate));const savedSales=(j.sales||[]).find((x:SalesPerson)=>x.id===saved.salesId&&x.active!==false);setSalesId(savedSales?.id||'');setClientId('');setClientName('');setAttention('');setAddress('')}finally{setMasterLoading(false)}})()},[reloadId]);
 useEffect(()=>{if(!reloadId){setQuoteLoading(false);return};(async()=>{setQuoteLoading(true);try{const r=await fetch(`/api/quotation/${reloadId}`,{cache:'no-store'});const q:StoredQuotation=await r.json();if(!r.ok)return setMsg((q as any).error||'Failed to reload');const c=q.content;setQuotationId(q.id);setQuotationNo(q.quotation_no);setOriginalContent(c);setDate(c.quotationDate);setValidity(c.validityDays);setVatRate(Number.isFinite(Number(c.vatRate))?Number(c.vatRate):11);setRfq(c.rfqNo||'');setSalesId(c.salesId);setClientId(c.clientId);setClientName(c.clientName||'');setAttention(c.attention||'');setAddress(c.address||'');setCompanyAddress(c.companyAddress||COMPANY_ADDRESS);setItems([...c.items,...Array.from({length:Math.max(0,10-c.items.length)},()=>blankRow())]);setNotes(c.notes?.length?[...c.notes]:['Items price exclude VAT','Payment condition: 30 days after issue invoice','Lead time is available after PO issued to Serveone','Franco Jakarta']);setMsg(`Loaded ${q.quotation_no}. If the final content is unchanged, the same quotation number will be reused.`)}finally{setQuoteLoading(false)}})()},[reloadId]);
 const sale=sales.find(x=>x.id===salesId),director=directors.find(x=>x.active!==false)||directors[0]||({id:'static-mr-herry',name:'Mr. Herry',title:'President Director',signature_path:'/signature-mr-herry.png',active:true} as Director);
 const clientGroups=useMemo(()=>{const byName=new Map<string,MemberRecord>();for(const m of members){const key=m.op_unit_name.trim();if(key&&!byName.has(key.toLowerCase()))byName.set(key.toLowerCase(),m)}return [...byName.values()].sort((a,b)=>alpha(a.op_unit_name,b.op_unit_name))},[members]);
 const clientRows=useMemo(()=>clientName?members.filter(m=>m.op_unit_name===clientName&&m.active!==false).sort((a,b)=>alpha(a.member_name,b.member_name)):[],[members,clientName]);
 const clientBase=clientRows[0]||members.find(m=>m.op_unit_name===clientName);
 const attentions=useMemo(()=>clientRows.map(m=>({value:m.member_name,label:m.member_name})),[clientRows]);
 const subtotal=useMemo(()=>items.reduce((s,x)=>s+(Number(x.qty)||0)*(Number(x.unitPrice)||0),0),[items]);
 const vatAmount=useMemo(()=>subtotal*(Number(vatRate)||0)/100,[subtotal,vatRate]);
 const total=useMemo(()=>subtotal+vatAmount,[subtotal,vatAmount]);
 const preview=clientBase?`SMI/${date.slice(0,7)}/${quotationNo?quotationNo.split('/').pop():'AUTO'}`:'Select client first';
 function savePreference(next:{salesId?:string;vatRate?:number}){if(reloadId)return;let current={};try{current=JSON.parse(localStorage.getItem(PREF_KEY)||'{}')}catch{}localStorage.setItem(PREF_KEY,JSON.stringify({...current,...next}))}
 function rememberVat(value:number){let current={};try{current=JSON.parse(localStorage.getItem(PREF_KEY)||'{}')}catch{}localStorage.setItem(PREF_KEY,JSON.stringify({...current,vatRate:value}))}
 function clearInvalid(key:RequiredField){setInvalid(current=>{if(!current.has(key))return current;const next=new Set(current);next.delete(key);return next})}
 function chooseSales(id:string){setSalesId(id);clearInvalid('sales');savePreference({salesId:id})}
 function chooseClient(name:string){const rows=members.filter(x=>x.op_unit_name===name).sort((a,b)=>alpha(a.member_name,b.member_name));const base=rows[0];setClientName(name);setClientId(base?.id||'');setAttention('');setAddress(base?.address||'');clearInvalid('client');setInvalid(current=>{const next=new Set(current);next.delete('attention');return next});if(!quotationId)setQuotationNo('')}
 function chooseAttention(name:string){setAttention(name);clearInvalid('attention')}
 function content():QuoteContent{const sm=clientBase||members.find(x=>x.id===clientId);const sameSales=originalContent?.salesId===salesId;return {quotationDate:date,validityDays:validity,vatRate,paymentCondition:'',rfqNo:rfq,salesId,salesName:sameSales?originalContent!.salesName:(sale?.name||''),salesEmail:sameSales?originalContent!.salesEmail:(sale?.email||''),salesPhone:sameSales?originalContent!.salesPhone:(sale?.phone||''),clientId:sm?.id||clientId,clientName:clientName||sm?.op_unit_name||'',clientNm:'',clientCode:'',attention,address:address||clientBase?.address||'',items,notes,directorId:director?.id||'',directorName:director?.name||'',directorTitle:director?.title||'Sign',directorSignaturePath:'/signature-mr-herry.png',companyName:COMPANY_NAME,companyAddress}}
 function validateRequired(){const next=new Set<RequiredField>();if(!date)next.add('date');if(!Number.isFinite(Number(validity))||Number(validity)<=0)next.add('validity');if(!salesId)next.add('sales');if(!clientName)next.add('client');if(!attention)next.add('attention');setInvalid(next);if(next.size){setMsg('Please complete all required fields highlighted in red.');setTimeout(()=>document.querySelector('[data-invalid="true"]')?.scrollIntoView({behavior:'smooth',block:'center'}),40);return false}return true}
 async function download(format:'excel'|'pdf'){setMsg('');if(!validateRequired())return;setBusy(format);try{const prep=await fetch('/api/quotation/prepare',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sourceQuotationId:quotationId,content:content()})});const q=await prep.json();if(!prep.ok)throw new Error(q.error||'Failed to prepare quotation');setQuotationId(q.id);setQuotationNo(q.quotation_no);setOriginalContent(q.content);const r=await fetch(`/api/export/${format}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({quotationId:q.id})});if(!r.ok)throw new Error(await r.text());const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${q.quotation_no.replace(/[^a-zA-Z0-9._-]/g,'_')}.${format==='excel'?'xlsx':'pdf'}`;a.click();URL.revokeObjectURL(url);setMsg(`${q.quotation_no} downloaded as ${format.toUpperCase()}.`);if(reloadId!==q.id)router.replace(`/?reload=${q.id}`)}catch(e){setMsg(e instanceof Error?e.message:'Failed')}finally{setBusy(null)}}
 function moveNote(i:number,dir:-1|1){const j=i+dir;if(j<0||j>=notes.length)return;const next=[...notes];[next[i],next[j]]=[next[j],next[i]];setNotes(next)}
 return <>
 <LoadingOverlay show={masterLoading||quoteLoading||!!busy} label={busy?`Generating ${busy.toUpperCase()}...`:'Loading quotation data...'}/>
 <header className="page-head"><div><h1>Create Quotation</h1><p>Create, revise, and reprint quotation documents.</p></div><div className="quote-badge"><small>Quotation Number</small><b>{quotationNo||preview}</b></div></header>{msg&&<div className="notice">{msg}</div>}
 <div className="two-col"><section className={`panel quotation-info ${sale?'has-sales':''}`}><h2>Quotation Information</h2><div className="form-grid"><label className={`${invalid.has('date')?'required-error ':''}${date?'filled-field':''}`.trim()} data-invalid={invalid.has('date')?'true':undefined}>Date<input type="date" value={date} onChange={e=>{setDate(e.target.value);clearInvalid('date')}}/></label><label className={`${invalid.has('validity')?'required-error ':''}${Number(validity)>0?'filled-field':''}`.trim()} data-invalid={invalid.has('validity')?'true':undefined}>Validity<div className="suffix-input"><input type="number" min="1" value={validity} onChange={e=>{setValidity(Number(e.target.value)||0);clearInvalid('validity')}}/><span>Days</span></div></label><label className={`rfq-field ${rfq.trim()?'filled-field':''}`.trim()}><span className="label-line">RFQ No. <small>(Optional)</small></span><input value={rfq} onChange={e=>setRfq(e.target.value)}/></label><SearchSelect id="sales-pic-field" className={`sales-field ${salesId?'filled-field':''}`.trim()} label="Sales PIC" value={salesId} error={invalid.has('sales')} options={sales.filter(x=>x.active!==false||x.id===salesId).sort((a,b)=>alpha(a.name,b.name)).map(x=>({value:x.id,label:x.name,subtitle:[x.email,x.phone].filter(Boolean).join(' · ')}))} onChange={chooseSales}/></div></section>
 <section className="panel"><h2>Client Information</h2><div className="stack"><SearchSelect id="client-field" className={clientName?'filled-field':''} label="Client" value={clientName} error={invalid.has('client')} options={clientGroups.map(x=>({value:x.op_unit_name,label:x.op_unit_name}))} onChange={chooseClient}/><SearchSelect id="attention-field" className={attention?'filled-field':''} label="Attention" value={attention} error={invalid.has('attention')} options={attentions} onChange={chooseAttention} placeholder={clientName?'Select Attention...':'Select client first'} disabled={!clientName}/><label className={`plain-value-label ${address?'filled-field':''}`.trim()}>Address<textarea value={address} rows={3} readOnly/></label></div></section></div>
 <section className="panel items-panel"><div className="panel-title"><div><h2>Items</h2><p>Spreadsheet-style grid. Paste from Excel and drag the blue fill handle to copy values.</p></div><div className="add-many"><input aria-label="Rows to add" type="number" inputMode="numeric" min="1" max="100" value={rowsToAdd} onKeyDown={e=>{if(['-','+','e','E'].includes(e.key))e.preventDefault()}} onChange={e=>setRowsToAdd(Math.min(100,Math.max(1,Number(e.target.value)||10)))}/><button className="btn ghost" onClick={()=>setItems([...items,...Array.from({length:rowsToAdd},()=>blankRow())])}>+ Add Rows</button></div></div><SpreadsheetGrid rows={items} setRows={setItems} uoms={uoms}/><div className="totals-box"><div><span>Total Amount</span><b>IDR {new Intl.NumberFormat('id-ID').format(subtotal)}</b></div><div><span>Total VAT <span className="vat-inline"><input aria-label="VAT percentage" type="number" min="0" max="100" step="0.01" value={vatRate} onChange={e=>{const n=Math.max(0,Number(e.target.value)||0);setVatRate(n);rememberVat(n)}}/><em>%</em></span></span><b>IDR {new Intl.NumberFormat('id-ID').format(vatAmount)}</b></div><div className="total-incl"><span>Total Amount Including VAT</span><b>IDR {new Intl.NumberFormat('id-ID').format(total)}</b></div></div></section>
 <div className="two-col bottom"><section className="panel"><div className="panel-title"><h2>Notes</h2><button className="btn ghost" onClick={()=>setNotes([...notes,''])}>+ Add Point</button></div><div className="notes">{notes.map((n,i)=><div className="note-row reorderable-note" key={`${i}-${n}`}><span>{i+1}.</span><input value={n} onChange={e=>setNotes(notes.map((x,j)=>j===i?e.target.value:x))}/><div className="note-actions"><button className="icon-only-button note-move" title="Move up" aria-label={`Move note ${i+1} up`} disabled={i===0} onClick={()=>moveNote(i,-1)}><UiIcon name="chevronUp" size={14}/></button><button className="icon-only-button note-move" title="Move down" aria-label={`Move note ${i+1} down`} disabled={i===notes.length-1} onClick={()=>moveNote(i,1)}><UiIcon name="chevronDown" size={14}/></button><button className="note-delete" title="Delete note" aria-label={`Delete note ${i+1}`} onClick={()=>setNotes(notes.filter((_,j)=>j!==i))}><UiIcon name="remove" size={16}/></button></div></div>)}</div></section><section className="panel company-card"><h2>Issuer</h2><b>{COMPANY_NAME}</b><p>{companyAddress}</p></section></div>
 <div className="action-bar"><div><small>{quotationNo?'Current quotation':'New quotation'}</small><b>{quotationNo||preview}</b></div><div><button disabled={!!busy} className="btn excel icon-btn" onClick={()=>download('excel')}><UiIcon name="excel"/>{busy==='excel'?'Generating...':'Download Excel'}</button><button disabled={!!busy} className="btn pdf icon-btn" onClick={()=>download('pdf')}><UiIcon name="pdf"/>{busy==='pdf'?'Generating...':'Download PDF'}</button></div></div>
 </>
}
