'use client';
import {useEffect,useMemo,useState} from 'react';
import {useSearchParams,useRouter} from 'next/navigation';
import {SearchSelect} from './SearchSelect';
import SpreadsheetGrid,{blankRow} from './SpreadsheetGrid';
import type {Director,MemberRecord,QuoteContent,QuoteItem,SalesPerson,StoredQuotation,Uom} from '@/lib/types';
import {COMPANY_ADDRESS,COMPANY_NAME} from '@/lib/constants';
import UiIcon from './UiIcon';
const todayJakarta=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta'}).format(new Date());
const tenRows=()=>Array.from({length:10},()=>blankRow());
const PREF_KEY='serveone-create-quotation-preferences';
export default function QuotationApp(){
 const sp=useSearchParams(),router=useRouter();const reloadId=sp.get('reload');
 const [sales,setSales]=useState<SalesPerson[]>([]),[members,setMembers]=useState<MemberRecord[]>([]),[directors,setDirectors]=useState<Director[]>([]),[uoms,setUoms]=useState<Uom[]>([]);
 const [salesId,setSalesId]=useState(''),[clientId,setClientId]=useState('');
 const [attention,setAttention]=useState(''),[clientNm,setClientNm]=useState(''),[address,setAddress]=useState(''),[items,setItems]=useState<QuoteItem[]>(tenRows()),[notes,setNotes]=useState<string[]>(['Items price exclude VAT','Payment condition: 30 days after issue invoice','Lead time is available after PO issued to Serveone','Franco Jakarta']);
 const [date,setDate]=useState(todayJakarta()),[validity,setValidity]=useState(30),[vatRate,setVatRate]=useState(11),[rfq,setRfq]=useState('');
 const [quotationId,setQuotationId]=useState<string|null>(null),[quotationNo,setQuotationNo]=useState(''),[originalContent,setOriginalContent]=useState<QuoteContent|null>(null),[busy,setBusy]=useState<'excel'|'pdf'|null>(null),[msg,setMsg]=useState(''),[rowsToAdd,setRowsToAdd]=useState(1);
 useEffect(()=>{(async()=>{const r=await fetch('/api/masters',{cache:'no-store'});const j=await r.json();if(!r.ok)return setMsg(j.error||'Failed to load database');setSales(j.sales||[]);setMembers(j.members||[]);setDirectors(j.directors||[]);setUoms(j.uoms||[]);if(reloadId)return;let saved:{salesId?:string;clientId?:string;vatRate?:number}={};try{saved=JSON.parse(localStorage.getItem(PREF_KEY)||'{}')}catch{}if(Number.isFinite(Number(saved.vatRate)))setVatRate(Number(saved.vatRate));const savedSales=(j.sales||[]).find((x:SalesPerson)=>x.id===saved.salesId&&x.active!==false);setSalesId(savedSales?.id||j.sales?.find((x:SalesPerson)=>x.active!==false)?.id||'');const savedMember=(j.members||[]).find((x:MemberRecord)=>x.id===saved.clientId);if(savedMember){setClientId(savedMember.id);setAttention(savedMember.member_name||'');setClientNm(savedMember.client_name||'');setAddress(savedMember.address||'')}})()},[reloadId]);
 useEffect(()=>{if(!reloadId)return;(async()=>{const r=await fetch(`/api/quotation/${reloadId}`,{cache:'no-store'});const q:StoredQuotation=await r.json();if(!r.ok)return setMsg((q as any).error||'Failed to reload');const c=q.content;setQuotationId(q.id);setQuotationNo(q.quotation_no);setOriginalContent(c);setDate(c.quotationDate);setValidity(c.validityDays);setVatRate(Number.isFinite(Number(c.vatRate))?Number(c.vatRate):11);setRfq(c.rfqNo||'');setSalesId(c.salesId);setClientId(c.clientId);setAttention(c.attention);setClientNm(c.clientNm||'');setAddress(c.address);setItems([...c.items,...Array.from({length:Math.max(0,10-c.items.length)},()=>blankRow())]);const paymentNote=c.paymentCondition?`Payment condition: ${c.paymentCondition}`:'';setNotes([...(c.notes.length?c.notes:[]),...(paymentNote&&!c.notes.some(n=>n.toLowerCase().includes('payment condition'))?[paymentNote]:[])]);setMsg(`Loaded ${q.quotation_no}. If the final content is unchanged, the same quotation number will be reused.`)})()},[reloadId]);
 const sale=sales.find(x=>x.id===salesId),director=directors.find(x=>x.active!==false)||directors[0]||({id:'static-mr-herry',name:'Mr. Herry',title:'President Director',signature_path:'/signature-mr-herry.png',active:true} as Director),selectedMember=members.find(x=>x.id===clientId);
 const clientGroups=useMemo(()=>{const seen=new Set<string>();return members.filter(m=>{const k=`${m.op_unit_name}|||${m.client_name}`;if(seen.has(k))return false;seen.add(k);return true})},[members]);
 const attentions=useMemo(()=>selectedMember?members.filter(m=>m.op_unit_name===selectedMember.op_unit_name&&m.client_name===selectedMember.client_name):[],[members,selectedMember]);
 const subtotal=useMemo(()=>items.reduce((s,x)=>s+(Number(x.qty)||0)*(Number(x.unitPrice)||0),0),[items]);
 const vatAmount=useMemo(()=>subtotal*(Number(vatRate)||0)/100,[subtotal,vatRate]);
 const total=useMemo(()=>subtotal+vatAmount,[subtotal,vatAmount]);
 const preview=selectedMember?`SMI/${selectedMember.client_code}/${date.slice(0,7).replace('-','.')}/${quotationNo?quotationNo.split('/').pop():'AUTO'}`:'Select client first';
 function savePreference(next:{salesId?:string;clientId?:string;vatRate?:number}){if(reloadId)return;let current={};try{current=JSON.parse(localStorage.getItem(PREF_KEY)||'{}')}catch{}localStorage.setItem(PREF_KEY,JSON.stringify({...current,...next}))}
 function rememberVat(value:number){let current={};try{current=JSON.parse(localStorage.getItem(PREF_KEY)||'{}')}catch{}localStorage.setItem(PREF_KEY,JSON.stringify({...current,vatRate:value}))}
 function chooseSales(id:string){setSalesId(id);savePreference({salesId:id})}
 function chooseClient(id:string){const m=members.find(x=>x.id===id);setClientId(id);setAttention(m?.member_name||'');setClientNm(m?.client_name||'');setAddress(m?.address||'');savePreference({clientId:id});if(!quotationId)setQuotationNo('')}
 function chooseAttention(name:string){setAttention(name);const m=attentions.find(x=>x.member_name.toLowerCase()===name.toLowerCase());if(m){setClientId(m.id);setClientNm(m.client_name);setAddress(m.address)}}
 async function addAttention(){const name=attention.trim();if(!name||!selectedMember)return; if(attentions.some(x=>x.member_name.toLowerCase()===name.toLowerCase()))return;const r=await fetch('/api/members',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({row:{member_name:name,op_unit_name:selectedMember.op_unit_name,client_name:selectedMember.client_name,address:selectedMember.address,client_code:selectedMember.client_code,active:true}})});const j=await r.json();if(r.ok){setMembers(v=>[...v,j]);setClientId(j.id);setMsg('Attention added to Database.')}else setMsg(j.error||'Failed to add Attention')}
 function content():QuoteContent{const sm=members.find(x=>x.id===clientId)||selectedMember;const sameSales=originalContent?.salesId===salesId;return {quotationDate:date,validityDays:validity,vatRate,paymentCondition:'',rfqNo:rfq,salesId,salesName:sameSales?originalContent!.salesName:(sale?.name||''),salesEmail:sameSales?originalContent!.salesEmail:(sale?.email||''),salesPhone:sameSales?originalContent!.salesPhone:(sale?.phone||''),clientId:sm?.id||clientId,clientName:sm?.op_unit_name||'',clientNm:sm?.client_name||clientNm,clientCode:sm?.client_code||'',attention,address,items,notes,directorId:director?.id||'',directorName:director?.name||'',directorTitle:director?.title||'Sign',directorSignaturePath:'/signature-mr-herry.png',companyName:COMPANY_NAME,companyAddress:COMPANY_ADDRESS}}
 async function download(format:'excel'|'pdf'){setMsg('');if(!selectedMember||!salesId)return setMsg('Client and Sales PIC are required.');setBusy(format);try{const prep=await fetch('/api/quotation/prepare',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sourceQuotationId:quotationId,content:content()})});const q=await prep.json();if(!prep.ok)throw new Error(q.error||'Failed to prepare quotation');setQuotationId(q.id);setQuotationNo(q.quotation_no);setOriginalContent(q.content);const r=await fetch(`/api/export/${format}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({quotationId:q.id})});if(!r.ok)throw new Error(await r.text());const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${q.quotation_no.replace(/[^a-zA-Z0-9._-]/g,'_')}.${format==='excel'?'xlsx':'pdf'}`;a.click();URL.revokeObjectURL(url);setMsg(`${q.quotation_no} downloaded as ${format.toUpperCase()}.`);if(reloadId!==q.id)router.replace(`/?reload=${q.id}`)}catch(e){setMsg(e instanceof Error?e.message:'Failed')}finally{setBusy(null)}}
 return <>
 <header className="page-head"><div><h1>Create Quotation</h1><p>Create, revise, and reprint quotation documents.</p></div><div className="quote-badge"><small>Quotation Number</small><b>{quotationNo||preview}</b></div></header>{msg&&<div className="notice">{msg}</div>}
 <div className="two-col"><section className="panel"><h2>Quotation Information</h2><div className="form-grid"><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Validity<div className="suffix-input"><input type="number" min="1" value={validity} onChange={e=>setValidity(Number(e.target.value)||30)}/><span>Days</span></div></label><label><span className="label-line">RFQ No. <small>(Optional)</small></span><input value={rfq} onChange={e=>setRfq(e.target.value)}/></label><SearchSelect label="Sales PIC" value={salesId} options={sales.filter(x=>x.active!==false||x.id===salesId).map(x=>({value:x.id,label:x.name,subtitle:[x.email,x.phone].filter(Boolean).join(' · ')}))} onChange={chooseSales}/></div></section>
 <section className="panel"><h2>Client Information</h2><div className="stack"><SearchSelect label="Client" value={selectedMember?.id||clientId} options={clientGroups.map(x=>({value:x.id,label:x.op_unit_name,subtitle:`${x.client_name} · ${x.client_code}`}))} onChange={chooseClient}/><label>Attention<div className="combo-row"><input list="attention-list" value={attention} onChange={e=>chooseAttention(e.target.value)} placeholder="Select or type Member Nm."/><datalist id="attention-list">{attentions.map(x=><option key={x.id} value={x.member_name}/>)}</datalist><button type="button" className="btn ghost" onClick={addAttention}>+ Add</button></div></label><label>Address<textarea value={address} rows={3} readOnly/></label></div></section></div>
 <section className="panel items-panel"><div className="panel-title"><div><h2>Items</h2><p>Spreadsheet-style grid. Paste from Excel and drag the blue fill handle to copy values.</p></div><div className="add-many"><input aria-label="Rows to add" type="number" min="1" max="100" value={rowsToAdd} onChange={e=>setRowsToAdd(Math.min(100,Math.max(1,Number(e.target.value)||1)))}/><button className="btn ghost" onClick={()=>setItems([...items,...Array.from({length:rowsToAdd},()=>blankRow())])}>+ Add Rows</button></div></div><SpreadsheetGrid rows={items} setRows={setItems} uoms={uoms}/><div className="totals-box"><div><span>Total Amount</span><b>IDR {new Intl.NumberFormat('id-ID').format(subtotal)}</b></div><div><span>Total VAT <span className="vat-inline"><input aria-label="VAT percentage" type="number" min="0" max="100" step="0.01" value={vatRate} onChange={e=>{const n=Math.max(0,Number(e.target.value)||0);setVatRate(n);rememberVat(n)}}/><em>%</em></span></span><b>IDR {new Intl.NumberFormat('id-ID').format(vatAmount)}</b></div><div className="total-incl"><span>Total Amount Include VAT</span><b>IDR {new Intl.NumberFormat('id-ID').format(total)}</b></div></div></section>
 <div className="two-col bottom"><section className="panel"><div className="panel-title"><h2>Notes</h2><button className="btn ghost" onClick={()=>setNotes([...notes,''])}>+ Add Point</button></div><div className="notes">{notes.map((n,i)=><div className="note-row" key={i}><span>{i+1}.</span><input value={n} onChange={e=>setNotes(notes.map((x,j)=>j===i?e.target.value:x))}/><button onClick={()=>setNotes(notes.filter((_,j)=>j!==i))}>×</button></div>)}</div></section><section className="panel company-card"><h2>Issuer</h2><b>{COMPANY_NAME}</b><p>{COMPANY_ADDRESS}</p></section></div>
 <div className="action-bar"><div><small>{quotationNo?'Current quotation':'New quotation'}</small><b>{quotationNo||preview}</b></div><div><button disabled={!!busy} className="btn excel icon-btn" onClick={()=>download('excel')}><UiIcon name="excel"/>{busy==='excel'?'Generating...':'Download Excel'}</button><button disabled={!!busy} className="btn pdf icon-btn" onClick={()=>download('pdf')}><UiIcon name="pdf"/>{busy==='pdf'?'Generating...':'Download PDF'}</button></div></div>
 </>}
