'use client';
import { useEffect,useMemo,useRef,useState } from 'react';
export type Option={value:string;label:string;subtitle?:string};
export function SearchSelect({label,value,options,onChange,placeholder='Select...',disabled=false,error=false,id,className='' }:{label:string;value:string;options:Option[];onChange:(v:string)=>void;placeholder?:string;disabled?:boolean;error?:boolean;id?:string;className?:string}){
 const [open,setOpen]=useState(false),[q,setQ]=useState(''); const ref=useRef<HTMLDivElement>(null); const selected=options.find(x=>x.value===value);
 const filtered=useMemo(()=>options.filter(x=>(x.label+' '+(x.subtitle||'')).toLowerCase().includes(q.toLowerCase())),[options,q]);
 useEffect(()=>{const fn=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setOpen(false)};document.addEventListener('mousedown',fn);return()=>document.removeEventListener('mousedown',fn)},[]);
 return <div id={id} className={`field ${className} ${error?'field-error':''}`.trim()} data-invalid={error?'true':undefined} ref={ref}><label>{label}</label><button type="button" disabled={disabled} className="select-trigger" onClick={()=>setOpen(!open)}><span className="select-value"><span>{selected?.label||placeholder}</span>{selected?.subtitle&&<small>{selected.subtitle}</small>}</span><svg aria-hidden="true" viewBox="0 0 24 24"><path d="m7 10 5 5 5-5"/></svg></button>{open&&<div className="select-popover"><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search..."/><div className="select-options">{filtered.map(o=><button type="button" key={o.value} onClick={()=>{onChange(o.value);setOpen(false);setQ('')}}><span>{o.label}</span>{o.subtitle&&<small>{o.subtitle}</small>}</button>)}{!filtered.length&&<div className="empty">No data</div>}</div></div>}</div>
}
