'use client';
import {useEffect,useRef,useState} from 'react';
import type {ClipboardEvent,KeyboardEvent,PointerEvent as ReactPointerEvent} from 'react';
import type {QuoteItem,Uom} from '@/lib/types';
import {formatUomLabel} from '@/lib/uoms';
import UiIcon from './UiIcon';

const cols:(keyof QuoteItem)[]=['productName','spec','brand','user','leadTime','qty','uom','unitPrice','remarks'];
const labels=['Item / Description','Specification','Brand','User','Lead Time (Days)','Qty','UOM','Unit Price','Remarks'];
const USER_HISTORY_KEY='serveone-item-users-v1';
const idr=new Intl.NumberFormat('id-ID');
const numberValue=(v:string)=>Math.max(0,Number(v.replace(/[^0-9.-]/g,''))||0);
export const blankRow=():QuoteItem=>({code:'',productName:'',spec:'',brand:'',user:'',leadTime:'',qty:0,uom:'EA',unitPrice:0,remarks:''});

export default function SpreadsheetGrid({rows,setRows,uoms}:{rows:QuoteItem[];setRows:(r:QuoteItem[])=>void;uoms:Uom[]}){
 const [active,setActive]=useState<[number,number]>([0,0]);
 const [fill,setFill]=useState<{r:number;c:number;toR:number;toC:number}|null>(null);
 const [userHistory,setUserHistory]=useState<string[]>(()=>{if(typeof window==='undefined')return[];try{return JSON.parse(localStorage.getItem(USER_HISTORY_KEY)||'[]')}catch{return[]}});
 const fillRef=useRef(fill);fillRef.current=fill;
 useEffect(()=>{let live=true;(async()=>{try{const r=await fetch('/api/item-users',{cache:'no-store'});if(!r.ok)return;const j=await r.json();if(!live||!Array.isArray(j.users))return;setUserHistory(current=>{const merged=[...current,...j.users].map(String).map(x=>x.trim()).filter(Boolean);return [...new Map(merged.map(x=>[x.toLowerCase(),x])).values()].slice(0,100)})}catch{}})();return()=>{live=false}},[]);
 const patch=(r:number,c:number,v:string)=>{const next=rows.map(x=>({...x}));const key=cols[c];(next[r] as any)[key]=key==='qty'||key==='unitPrice'?numberValue(v):v;setRows(next)};
 const onPaste=(e:ClipboardEvent,r:number,c:number)=>{const txt=e.clipboardData.getData('text/plain');if(!txt.includes('\t')&&!txt.includes('\n'))return;e.preventDefault();const matrix=txt.replace(/\r/g,'').split('\n').filter((x,i,a)=>x||i<a.length-1).map(x=>x.split('\t'));const next=rows.map(x=>({...x}));while(next.length<r+matrix.length)next.push(blankRow());matrix.forEach((line,ri)=>line.forEach((v,ci)=>{const cc=c+ci;if(cc>=cols.length)return;const key=cols[cc];(next[r+ri] as any)[key]=key==='qty'||key==='unitPrice'?numberValue(v):v}));setRows(next)};
 const focusCell=(r:number,c:number)=>{setActive([r,c]);requestAnimationFrame(()=>document.querySelector<HTMLInputElement|HTMLSelectElement>(`[data-cell="${r}-${c}"]`)?.focus())};
 const keyNav=(e:KeyboardEvent,r:number,c:number)=>{if(e.key==='Tab'){e.preventDefault();const nc=e.shiftKey?c-1:c+1;if(nc<0&&r>0)focusCell(r-1,cols.length-1);else if(nc>=cols.length){if(r===rows.length-1)setRows([...rows,blankRow()]);focusCell(Math.min(r+1,rows.length),0)}else focusCell(r,nc)}else if(e.key==='ArrowDown'&&!(e.currentTarget as HTMLInputElement).selectionStart){focusCell(Math.min(rows.length-1,r+1),c)}else if(e.key==='ArrowUp'&&!(e.currentTarget as HTMLInputElement).selectionStart){focusCell(Math.max(0,r-1),c)}};
 const startFill=(e:ReactPointerEvent,r:number,c:number)=>{e.preventDefault();e.stopPropagation();(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);setFill({r,c,toR:r,toC:c})};
 const moveFill=(e:ReactPointerEvent)=>{if(!fillRef.current)return;const el=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-grid-cell]') as HTMLElement|null;if(!el)return;const rr=Number(el.dataset.r),cc=Number(el.dataset.c);if(Number.isFinite(rr)&&Number.isFinite(cc))setFill(f=>f?{...f,toR:rr,toC:cc}:f)};
 const endFill=()=>{const f=fillRef.current;if(!f)return;const next=rows.map(x=>({...x}));const source=(rows[f.r] as any)[cols[f.c]];for(let r=Math.min(f.r,f.toR);r<=Math.max(f.r,f.toR);r++)for(let c=Math.min(f.c,f.toC);c<=Math.max(f.c,f.toC);c++)if(r!==f.r||c!==f.c)(next[r] as any)[cols[c]]=source;setRows(next);setFill(null)};
 useEffect(()=>{const up=()=>fillRef.current&&endFill();window.addEventListener('pointerup',up);return()=>window.removeEventListener('pointerup',up)});
 const inFill=(r:number,c:number)=>!!fill&&r>=Math.min(fill.r,fill.toR)&&r<=Math.max(fill.r,fill.toR)&&c>=Math.min(fill.c,fill.toC)&&c<=Math.max(fill.c,fill.toC);
 const copyRow=(i:number)=>{const next=[...rows];next.splice(i+1,0,{...rows[i]});setRows(next)};
 const remove=(i:number)=>setRows(rows.length<=10?rows.map((x,j)=>j===i?blankRow():x):rows.filter((_,j)=>j!==i));
 const rememberUser=(value:string)=>{const name=value.trim();if(!name)return;setUserHistory(current=>{const next=[name,...current.filter(x=>x.toLowerCase()!==name.toLowerCase())].slice(0,100);localStorage.setItem(USER_HISTORY_KEY,JSON.stringify(next));return next})};
 const cell=(row:QuoteItem,r:number,k:keyof QuoteItem,c:number)=><td key={k} data-grid-cell data-r={r} data-c={c} className={`${active[0]===r&&active[1]===c?'cell-focus':''} ${inFill(r,c)?'fill-range':''}`} onPointerMove={moveFill}>{k==='uom'?<input className="uom-search-input" data-cell={`${r}-${c}`} list="uom-search-list" aria-label={`UOM row ${r+1}`} title={formatUomLabel(uoms.find(u=>u.code===String(row[k]||'EA'))||{code:String(row[k]||'EA'),name:''})} autoComplete="off" value={String(row[k]||'EA')} onFocus={()=>setActive([r,c])} onKeyDown={e=>keyNav(e,r,c)} onPaste={e=>onPaste(e,r,c)} onChange={e=>patch(r,c,e.target.value.toUpperCase())}/>:k==='unitPrice'?<div className="currency-input"><span>IDR</span><input data-cell={`${r}-${c}`} inputMode="numeric" value={row.unitPrice?idr.format(row.unitPrice):''} onFocus={()=>setActive([r,c])} onKeyDown={e=>keyNav(e,r,c)} onPaste={e=>onPaste(e,r,c)} onChange={e=>patch(r,c,e.target.value)}/></div>:<input data-cell={`${r}-${c}`} list={k==='user'?'item-user-history':undefined} autoComplete="off" value={k==='qty'&&!row.qty?'':String(row[k]??'')} type={k==='qty'?'number':'text'} min={k==='qty'?0:undefined} inputMode={k==='qty'?'decimal':undefined} onFocus={()=>setActive([r,c])} onBlur={e=>{if(k==='user')rememberUser(e.target.value)}} onKeyDown={e=>{if(k==='qty'&&['-','+','e','E'].includes(e.key)){e.preventDefault();return}keyNav(e,r,c)}} onPaste={e=>onPaste(e,r,c)} onChange={e=>patch(r,c,e.target.value)}/>} {active[0]===r&&active[1]===c&&<span className="fill-handle" title="Drag to copy" onPointerDown={e=>startFill(e,r,c)} onPointerMove={moveFill}/>}</td>;
 return <div className="sheet-wrap"><datalist id="item-user-history">{userHistory.map(x=><option key={x} value={x}/>)}</datalist><datalist id="uom-search-list">{uoms.map(u=><option key={u.id} value={u.code} label={formatUomLabel(u)}/>)}</datalist><div className="sheet-canvas"><table className="sheet"><thead><tr><th className="rowno">No</th>{labels.slice(0,-1).map(x=><th key={x}>{x}</th>)}<th>Amount</th><th>Remarks</th></tr></thead><tbody>{rows.map((row,r)=><tr key={r}><td className="rowno">{r+1}</td>{cols.slice(0,-1).map((k,c)=>cell(row,r,k,c))}<td className="amount-cell"><span>IDR</span><b>{idr.format((row.qty||0)*(row.unitPrice||0))}</b></td>{cell(row,r,'remarks',cols.length-1)}</tr>)}</tbody></table><div className="row-tools" aria-label="Row actions"><div className="row-tools-head">Actions</div>{rows.map((_,i)=><div className="row-tools-cell" key={i}><button type="button" title="Duplicate row" aria-label={`Duplicate row ${i+1}`} onClick={()=>copyRow(i)}><UiIcon name="duplicate" size={16}/></button><button type="button" className="remove-row" title="Remove row" aria-label={`Remove row ${i+1}`} onClick={()=>remove(i)}><UiIcon name="remove" size={16}/></button></div>)}</div></div><div className="sheet-hint">Paste directly from Excel. Drag the blue handle to repeat a value. User suggestions are remembered from previous quotations.</div></div>
}
