'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import type {ClipboardEvent,KeyboardEvent,PointerEvent as ReactPointerEvent,ChangeEvent} from 'react';
import type {QuoteItem,Uom} from '@/lib/types';
import {formatUomLabel} from '@/lib/uoms';

const cols:(keyof QuoteItem)[]=['code','productName','spec','brand','user','leadTime','qty','uom','unitPrice','remarks'];
const labels=['Code','Item / Description','Specification','Brand','User','Lead Time','Qty','UOM','Unit Price','Remarks'];
const USER_HISTORY_KEY='serveone-item-users-v1';
const idr=new Intl.NumberFormat('id-ID');
const numberValue=(v:string)=>Math.max(0,Number(v.replace(/[^0-9.-]/g,''))||0);
export const blankRow=():QuoteItem=>({code:'',productName:'',spec:'',brand:'',user:'',leadTime:'',leadTimeUnit:'Days',qty:0,uom:'EA',unitPrice:0,remarks:''});

function UomPicker({value,uoms,onChange,onFocus,onKeyDown,onPaste,cellId}:{value:string;uoms:Uom[];onChange:(v:string)=>void;onFocus:()=>void;onKeyDown:(e:KeyboardEvent<HTMLInputElement>)=>void;onPaste:(e:ClipboardEvent<HTMLInputElement>)=>void;cellId:string}){
 const [open,setOpen]=useState(false),[q,setQ]=useState('');
 const wrapRef=useRef<HTMLDivElement>(null),mainRef=useRef<HTMLInputElement>(null),searchRef=useRef<HTMLInputElement>(null);
 const [pos,setPos]=useState({top:0,left:0,width:156});
 const selected=String(value||'EA').toUpperCase();
 const filtered=useMemo(()=>{const needle=q.trim().toLowerCase();if(!needle)return uoms;return uoms.filter(u=>`${u.code} ${u.name||''}`.toLowerCase().includes(needle))},[uoms,q]);
 const close=()=>{setOpen(false);setQ('')};
 const place=()=>{const el=wrapRef.current;if(!el||typeof window==='undefined')return;const r=el.getBoundingClientRect(),w=156;setPos({top:r.bottom+4,left:Math.min(r.left,Math.max(8,window.innerWidth-w-8)),width:w})};
 const show=()=>{onFocus();setQ('');place();setOpen(true);requestAnimationFrame(()=>searchRef.current?.focus())};
 const choose=(code:string)=>{onChange(code.toUpperCase());close()};
 useEffect(()=>{if(!open)return;const outside=(e:MouseEvent)=>{const t=e.target as Node;if(wrapRef.current?.contains(t))return;const pop=document.querySelector('[data-uom-popover="true"]');if(pop?.contains(t))return;close()};const reposition=()=>place();const closeOnScroll=()=>close();document.addEventListener('mousedown',outside);window.addEventListener('resize',reposition);window.addEventListener('scroll',closeOnScroll,true);return()=>{document.removeEventListener('mousedown',outside);window.removeEventListener('resize',reposition);window.removeEventListener('scroll',closeOnScroll,true)}},[open]);
 const searchKey=(e:KeyboardEvent<HTMLInputElement>)=>{if(e.key==='Enter'){e.preventDefault();const exact=uoms.find(u=>u.code.toLowerCase()===q.trim().toLowerCase());const first=exact||filtered[0];if(first)choose(first.code);return}if(e.key==='Escape'){e.preventDefault();close();return}if(e.key==='Tab'){close();onKeyDown(e)}};
 const mainKey=(e:KeyboardEvent<HTMLInputElement>)=>{if((e.key==='Enter'||e.key==='ArrowDown')&&!open){e.preventDefault();show();return}onKeyDown(e)};
 const popup=open&&typeof document!=='undefined'?createPortal(<div data-uom-popover="true" className="uom-dropdown-popover" style={{top:pos.top,left:pos.left,width:pos.width}}><div className="uom-dropdown-search"><input ref={searchRef} autoFocus value={q} onChange={e=>setQ(e.target.value)} onKeyDown={searchKey} placeholder="Search UOM..."/></div><div className="uom-dropdown-list">{filtered.map(u=><button type="button" key={u.id} className={u.code===selected?'selected':''} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(u.code)}><span className="uom-code">{u.code}</span><span className="uom-name">{u.name?`(${String(u.name).toLowerCase().replace(/\b\w/g,m=>m.toUpperCase())})`:''}</span></button>)}{!filtered.length&&<div className="uom-dropdown-empty">No matching UOM</div>}</div></div>,document.body):null;
 return <div className="uom-picker" ref={wrapRef}><input ref={mainRef} className="uom-search-input" data-cell={cellId} value={selected} readOnly autoComplete="off" onFocus={()=>{if(!open)show();else onFocus()}} onClick={()=>{if(!open)show()}} onKeyDown={mainKey} onPaste={onPaste} title={formatUomLabel(uoms.find(u=>u.code===selected)||{code:selected,name:''})}/><button type="button" className="uom-picker-arrow" tabIndex={-1} aria-label="Open UOM list" onMouseDown={e=>e.preventDefault()} onClick={()=>open?close():show()}><span aria-hidden="true"/></button>{popup}</div>
}

function autoGrow(el:HTMLTextAreaElement){
  el.style.height='35px';
  el.style.height=`${Math.max(35,el.scrollHeight)}px`;
}

export default function SpreadsheetGrid({rows,setRows,uoms}:{rows:QuoteItem[];setRows:(r:QuoteItem[])=>void;uoms:Uom[]}){
 const [active,setActive]=useState<[number,number]>([0,0]);
 const [fill,setFill]=useState<{r:number;c:number;toR:number;toC:number}|null>(null);
 const [priceDraft,setPriceDraft]=useState<Record<number,string>>({});
 const [userHistory,setUserHistory]=useState<string[]>(()=>{if(typeof window==='undefined')return[];try{return JSON.parse(localStorage.getItem(USER_HISTORY_KEY)||'[]')}catch{return[]}});
 const fillRef=useRef(fill);fillRef.current=fill;
 useEffect(()=>{let live=true;(async()=>{try{const r=await fetch('/api/item-users',{cache:'no-store'});if(!r.ok)return;const j=await r.json();if(!live||!Array.isArray(j.users))return;setUserHistory(current=>{const merged=[...current,...j.users].map(String).map(x=>x.trim()).filter(Boolean);return [...new Map(merged.map(x=>[x.toLowerCase(),x])).values()].slice(0,100)})}catch{}})();return()=>{live=false}},[]);
 useEffect(()=>{document.querySelectorAll<HTMLTextAreaElement>('.sheet textarea.auto-wrap').forEach(autoGrow)},[rows]);
 const patch=(r:number,c:number,v:string)=>{const next=rows.map(x=>({...x}));const key=cols[c];(next[r] as any)[key]=key==='qty'||key==='unitPrice'?numberValue(v):v;setRows(next)};
 const patchLeadUnit=(r:number,v:'Days'|'Week')=>{const next=rows.map(x=>({...x}));next[r].leadTimeUnit=v;setRows(next)};
 const onPaste=(e:ClipboardEvent,r:number,c:number)=>{const txt=e.clipboardData.getData('text/plain');if(!txt.includes('\t')&&!txt.includes('\n'))return;e.preventDefault();const matrix=txt.replace(/\r/g,'').split('\n').filter((x,i,a)=>x||i<a.length-1).map(x=>x.split('\t'));const next=rows.map(x=>({...x}));while(next.length<r+matrix.length)next.push(blankRow());matrix.forEach((line,ri)=>line.forEach((v,ci)=>{const cc=c+ci;if(cc>=cols.length)return;const key=cols[cc];(next[r+ri] as any)[key]=key==='qty'||key==='unitPrice'?numberValue(v):v}));setRows(next)};
 const focusCell=(r:number,c:number)=>{setActive([r,c]);requestAnimationFrame(()=>document.querySelector<HTMLElement>(`[data-cell="${r}-${c}"]`)?.focus())};
 const keyNav=(e:KeyboardEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>,r:number,c:number)=>{if(e.key==='Tab'){e.preventDefault();const nc=e.shiftKey?c-1:c+1;if(nc<0&&r>0)focusCell(r-1,cols.length-1);else if(nc>=cols.length){if(r===rows.length-1)setRows([...rows,blankRow()]);focusCell(Math.min(r+1,rows.length),0)}else focusCell(r,nc)}};
 const startFill=(e:ReactPointerEvent,r:number,c:number)=>{e.preventDefault();e.stopPropagation();(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);setFill({r,c,toR:r,toC:c})};
 const moveFill=(e:ReactPointerEvent)=>{if(!fillRef.current)return;const el=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-grid-cell]') as HTMLElement|null;if(!el)return;const rr=Number(el.dataset.r),cc=Number(el.dataset.c);if(Number.isFinite(rr)&&Number.isFinite(cc))setFill(f=>f?{...f,toR:rr,toC:cc}:f)};
 const endFill=()=>{const f=fillRef.current;if(!f)return;const next=rows.map(x=>({...x}));const key=cols[f.c];const source=(rows[f.r] as any)[key];const sourceUnit=rows[f.r].leadTimeUnit||'Days';for(let rr=Math.min(f.r,f.toR);rr<=Math.max(f.r,f.toR);rr++)for(let cc=Math.min(f.c,f.toC);cc<=Math.max(f.c,f.toC);cc++)if(rr!==f.r||cc!==f.c){const k=cols[cc];(next[rr] as any)[k]=source;if(k==='leadTime')next[rr].leadTimeUnit=sourceUnit}setRows(next);setFill(null)};
 useEffect(()=>{const up=()=>fillRef.current&&endFill();window.addEventListener('pointerup',up);return()=>window.removeEventListener('pointerup',up)});
 const inFill=(r:number,c:number)=>!!fill&&r>=Math.min(fill.r,fill.toR)&&r<=Math.max(fill.r,fill.toR)&&c>=Math.min(fill.c,fill.toC)&&c<=Math.max(fill.c,fill.toC);
 const rememberUser=(value:string)=>{const name=value.trim();if(!name)return;setUserHistory(current=>{const next=[name,...current.filter(x=>x.toLowerCase()!==name.toLowerCase())].slice(0,100);localStorage.setItem(USER_HISTORY_KEY,JSON.stringify(next));return next})};
 const textAreaCell=(row:QuoteItem,r:number,k:keyof QuoteItem,c:number)=>{
   const val=String(row[k]??'');
   return <textarea className="auto-wrap" rows={1} data-cell={`${r}-${c}`} value={val} onFocus={e=>{setActive([r,c]);autoGrow(e.currentTarget)}} onKeyDown={e=>keyNav(e,r,c)} onPaste={e=>onPaste(e,r,c)} onChange={(e:ChangeEvent<HTMLTextAreaElement>)=>{patch(r,c,e.target.value);autoGrow(e.target)}}/>;
 };
 const cell=(row:QuoteItem,r:number,k:keyof QuoteItem,c:number)=><td key={k} data-grid-cell data-r={r} data-c={c} className={`${active[0]===r&&active[1]===c&&!['leadTime','uom'].includes(String(k))?'cell-focus':''} ${inFill(r,c)?'fill-range':''}`} onPointerMove={moveFill}>{k==='leadTime'?<div className="lead-time-input"><input className="lead-time-value" data-cell={`${r}-${c}`} value={String(row.leadTime||'')} onFocus={()=>setActive([r,c])} onKeyDown={e=>keyNav(e,r,c)} onPaste={e=>onPaste(e,r,c)} onChange={e=>patch(r,c,e.target.value)}/><select className="lead-time-unit" aria-label={`Lead time unit row ${r+1}`} value={row.leadTimeUnit||'Days'} onChange={e=>patchLeadUnit(r,e.target.value as 'Days'|'Week')}><option value="Days">Days</option><option value="Week">Week</option></select></div>:k==='uom'?<UomPicker cellId={`${r}-${c}`} value={String(row[k]||'EA')} uoms={uoms} onChange={v=>patch(r,c,v)} onFocus={()=>setActive([r,c])} onKeyDown={e=>keyNav(e,r,c)} onPaste={e=>onPaste(e,r,c)}/>:k==='unitPrice'?<div className="currency-input"><span>IDR</span><input data-cell={`${r}-${c}`} inputMode="numeric" value={priceDraft[r]!==undefined?priceDraft[r]:(row.unitPrice?idr.format(row.unitPrice):'')} onFocus={()=>{setActive([r,c]);setPriceDraft(d=>({...d,[r]:row.unitPrice?String(row.unitPrice):''}))}} onBlur={e=>{patch(r,c,e.target.value);setPriceDraft(d=>{const next={...d};delete next[r];return next})}} onKeyDown={e=>keyNav(e,r,c)} onPaste={e=>onPaste(e,r,c)} onChange={e=>setPriceDraft(d=>({...d,[r]:e.target.value.replace(/[^0-9]/g,'')}))}/></div>:k==='productName'||k==='spec'||k==='remarks'?textAreaCell(row,r,k,c):<input data-cell={`${r}-${c}`} list={k==='user'?'item-user-history':undefined} autoComplete="off" value={k==='qty'&&!row.qty?'':String(row[k]??'')} type={k==='qty'?'number':'text'} min={k==='qty'?0:undefined} inputMode={k==='qty'?'decimal':undefined} onFocus={()=>setActive([r,c])} onBlur={e=>{if(k==='user')rememberUser(e.target.value)}} onKeyDown={e=>{if(k==='qty'&&['-','+','e','E'].includes(e.key)){e.preventDefault();return}keyNav(e,r,c)}} onPaste={e=>onPaste(e,r,c)} onChange={e=>patch(r,c,e.target.value)}/>} {active[0]===r&&active[1]===c&&<span className="fill-handle" title="Drag to copy" onPointerDown={e=>startFill(e,r,c)} onPointerMove={moveFill}/>}</td>;
 return <div className="sheet-wrap"><datalist id="item-user-history">{userHistory.map(x=><option key={x} value={x}/>)}</datalist><div className="sheet-canvas"><table className="sheet"><colgroup><col className="col-no"/><col className="col-code"/><col className="col-item"/><col className="col-spec"/><col className="col-brand"/><col className="col-user"/><col className="col-lead"/><col className="col-qty"/><col className="col-uom"/><col className="col-price"/><col className="col-amount"/><col className="col-remarks"/></colgroup><thead><tr><th className="rowno">No</th>{labels.slice(0,-1).map(x=><th key={x}>{x}</th>)}<th>Amount</th><th>Remarks</th></tr></thead><tbody>{rows.map((row,r)=><tr key={r}><td className="rowno">{r+1}</td>{cols.slice(0,-1).map((k,c)=>cell(row,r,k,c))}<td className="amount-cell"><span>IDR</span><b>{idr.format((row.qty||0)*(row.unitPrice||0))}</b></td>{cell(row,r,'remarks',cols.length-1)}</tr>)}</tbody></table></div><div className="sheet-hint">Paste directly from Excel. Drag the blue handle to repeat a value. Lead Time defaults to Days. UOM is searchable. User suggestions are remembered from previous quotations.</div></div>
}
